/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.08 at 11:53:49 AM CDT 
//

package com.dell.isg.smi.wsman.command.entity.ipprotocolendpoint;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * com.dell.pg.spectre.common.protocol.command.wsman.entity.ipprotocolendpoint package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java representation of XML content can consist of schema
 * derived interfaces and classes representing the binding of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in this
 * class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _IPv4Address_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "IPv4Address");
    private final static QName _IPv6SubnetPrefixLength_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "IPv6SubnetPrefixLength");
    private final static QName _Caption_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "Caption");
    private final static QName _OtherTypeDescription_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "OtherTypeDescription");
    private final static QName _ProtocolIFType_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "ProtocolIFType");
    private final static QName _CommunicationStatus_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "CommunicationStatus");
    private final static QName _ElementName_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "ElementName");
    private final static QName _TransitioningToState_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "TransitioningToState");
    private final static QName _NameFormat_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "NameFormat");
    private final static QName _DetailedStatus_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "DetailedStatus");
    private final static QName _IPVersionSupport_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "IPVersionSupport");
    private final static QName _PrimaryStatus_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "PrimaryStatus");
    private final static QName _StatusDescriptions_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "StatusDescriptions");
    private final static QName _Description_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "Description");
    private final static QName _IPv6Address_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "IPv6Address");
    private final static QName _OtherEnabledState_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "OtherEnabledState");
    private final static QName _OperationalStatus_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "OperationalStatus");
    private final static QName _InstanceID_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "InstanceID");
    private final static QName _ProtocolType_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "ProtocolType");
    private final static QName _EnabledDefault_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "EnabledDefault");
    private final static QName _IPv6AddressType_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "IPv6AddressType");
    private final static QName _CIMIPProtocolEndpoint_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "CIM_IPProtocolEndpoint");
    private final static QName _HealthState_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "HealthState");
    private final static QName _RequestedState_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "RequestedState");
    private final static QName _SubnetMask_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "SubnetMask");
    private final static QName _OperatingStatus_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "OperatingStatus");
    private final static QName _InstallDate_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "InstallDate");
    private final static QName _AvailableRequestedStates_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "AvailableRequestedStates");
    private final static QName _Status_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "Status");
    private final static QName _AddressOrigin_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "AddressOrigin");
    private final static QName _Address_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "Address");
    private final static QName _AddressType_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "AddressType");
    private final static QName _PrefixLength_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "PrefixLength");
    private final static QName _TimeOfLastStateChange_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "TimeOfLastStateChange");
    private final static QName _EnabledState_QNAME = new QName("http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", "EnabledState");
    private final static QName _CimDateTimeCIMDateTime_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/common", "CIM_DateTime");


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
     * com.dell.pg.spectre.common.protocol.command.wsman.entity.ipprotocolendpoint
     * 
     */
    public ObjectFactory() {
    }


    /**
     * Create an instance of {@link CIMIPProtocolEndpointType }
     * 
     */
    public CIMIPProtocolEndpointType createCIMIPProtocolEndpointType() {
        return new CIMIPProtocolEndpointType();
    }


    /**
     * Create an instance of {@link NameFormat }
     * 
     */
    public NameFormat createNameFormat() {
        return new NameFormat();
    }


    /**
     * Create an instance of {@link SystemCreationClassName }
     * 
     */
    public SystemCreationClassName createSystemCreationClassName() {
        return new SystemCreationClassName();
    }


    /**
     * Create an instance of {@link CimUnsignedLong }
     * 
     */
    public CimUnsignedLong createCimUnsignedLong() {
        return new CimUnsignedLong();
    }


    /**
     * Create an instance of {@link QualifierSInt64 }
     * 
     */
    public QualifierSInt64 createQualifierSInt64() {
        return new QualifierSInt64();
    }


    /**
     * Create an instance of {@link CimUnsignedShort }
     * 
     */
    public CimUnsignedShort createCimUnsignedShort() {
        return new CimUnsignedShort();
    }


    /**
     * Create an instance of {@link CimAnySimpleType }
     * 
     */
    public CimAnySimpleType createCimAnySimpleType() {
        return new CimAnySimpleType();
    }


    /**
     * Create an instance of {@link CimShort }
     * 
     */
    public CimShort createCimShort() {
        return new CimShort();
    }


    /**
     * Create an instance of {@link RequestStateChangeINPUT.RequestedState }
     * 
     */
    public RequestStateChangeINPUT.RequestedState createRequestStateChangeINPUTRequestedState() {
        return new RequestStateChangeINPUT.RequestedState();
    }


    /**
     * Create an instance of {@link CimBoolean }
     * 
     */
    public CimBoolean createCimBoolean() {
        return new CimBoolean();
    }


    /**
     * Create an instance of {@link EnabledDefault }
     * 
     */
    public EnabledDefault createEnabledDefault() {
        return new EnabledDefault();
    }


    /**
     * Create an instance of {@link CimString }
     * 
     */
    public CimString createCimString() {
        return new CimString();
    }


    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }


    /**
     * Create an instance of {@link DetailedStatus }
     * 
     */
    public DetailedStatus createDetailedStatus() {
        return new DetailedStatus();
    }


    /**
     * Create an instance of {@link IPv6AddressType }
     * 
     */
    public IPv6AddressType createIPv6AddressType() {
        return new IPv6AddressType();
    }


    /**
     * Create an instance of {@link QualifierSArray }
     * 
     */
    public QualifierSArray createQualifierSArray() {
        return new QualifierSArray();
    }


    /**
     * Create an instance of {@link OperatingStatus }
     * 
     */
    public OperatingStatus createOperatingStatus() {
        return new OperatingStatus();
    }


    /**
     * Create an instance of {@link EnabledState }
     * 
     */
    public EnabledState createEnabledState() {
        return new EnabledState();
    }


    /**
     * Create an instance of {@link RequestStateChangeINPUT }
     * 
     */
    public RequestStateChangeINPUT createRequestStateChangeINPUT() {
        return new RequestStateChangeINPUT();
    }


    /**
     * Create an instance of {@link CimUnsignedInt }
     * 
     */
    public CimUnsignedInt createCimUnsignedInt() {
        return new CimUnsignedInt();
    }


    /**
     * Create an instance of {@link RequestStateChangeOUTPUT.ReturnValue }
     * 
     */
    public RequestStateChangeOUTPUT.ReturnValue createRequestStateChangeOUTPUTReturnValue() {
        return new RequestStateChangeOUTPUT.ReturnValue();
    }


    /**
     * Create an instance of {@link QualifierBoolean }
     * 
     */
    public QualifierBoolean createQualifierBoolean() {
        return new QualifierBoolean();
    }


    /**
     * Create an instance of {@link CimLong }
     * 
     */
    public CimLong createCimLong() {
        return new CimLong();
    }


    /**
     * Create an instance of {@link OperationalStatus }
     * 
     */
    public OperationalStatus createOperationalStatus() {
        return new OperationalStatus();
    }


    /**
     * Create an instance of {@link com.dell.isg.smi.wsman.command.entity.ipprotocolendpoint.RequestedState }
     * 
     */
    public com.dell.isg.smi.wsman.command.entity.ipprotocolendpoint.RequestedState createRequestedState() {
        return new com.dell.isg.smi.wsman.command.entity.ipprotocolendpoint.RequestedState();
    }


    /**
     * Create an instance of {@link PrimaryStatus }
     * 
     */
    public PrimaryStatus createPrimaryStatus() {
        return new PrimaryStatus();
    }


    /**
     * Create an instance of {@link HealthState }
     * 
     */
    public HealthState createHealthState() {
        return new HealthState();
    }


    /**
     * Create an instance of {@link ProtocolType }
     * 
     */
    public ProtocolType createProtocolType() {
        return new ProtocolType();
    }


    /**
     * Create an instance of {@link SystemName }
     * 
     */
    public SystemName createSystemName() {
        return new SystemName();
    }


    /**
     * Create an instance of {@link CimHexBinary }
     * 
     */
    public CimHexBinary createCimHexBinary() {
        return new CimHexBinary();
    }


    /**
     * Create an instance of {@link CimInt }
     * 
     */
    public CimInt createCimInt() {
        return new CimInt();
    }


    /**
     * Create an instance of {@link CimDouble }
     * 
     */
    public CimDouble createCimDouble() {
        return new CimDouble();
    }


    /**
     * Create an instance of {@link TransitioningToState }
     * 
     */
    public TransitioningToState createTransitioningToState() {
        return new TransitioningToState();
    }


    /**
     * Create an instance of {@link CimFloat }
     * 
     */
    public CimFloat createCimFloat() {
        return new CimFloat();
    }


    /**
     * Create an instance of {@link QualifierString }
     * 
     */
    public QualifierString createQualifierString() {
        return new QualifierString();
    }


    /**
     * Create an instance of {@link CommunicationStatus }
     * 
     */
    public CommunicationStatus createCommunicationStatus() {
        return new CommunicationStatus();
    }


    /**
     * Create an instance of {@link CimChar16 }
     * 
     */
    public CimChar16 createCimChar16() {
        return new CimChar16();
    }


    /**
     * Create an instance of {@link CimDateTime }
     * 
     */
    public CimDateTime createCimDateTime() {
        return new CimDateTime();
    }


    /**
     * Create an instance of {@link AvailableRequestedStates }
     * 
     */
    public AvailableRequestedStates createAvailableRequestedStates() {
        return new AvailableRequestedStates();
    }


    /**
     * Create an instance of {@link CimUnsignedByte }
     * 
     */
    public CimUnsignedByte createCimUnsignedByte() {
        return new CimUnsignedByte();
    }


    /**
     * Create an instance of {@link QualifierUInt32 }
     * 
     */
    public QualifierUInt32 createQualifierUInt32() {
        return new QualifierUInt32();
    }


    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }


    /**
     * Create an instance of {@link RequestStateChangeOUTPUT }
     * 
     */
    public RequestStateChangeOUTPUT createRequestStateChangeOUTPUT() {
        return new RequestStateChangeOUTPUT();
    }


    /**
     * Create an instance of {@link ProtocolIFType }
     * 
     */
    public ProtocolIFType createProtocolIFType() {
        return new ProtocolIFType();
    }


    /**
     * Create an instance of {@link CreationClassName }
     * 
     */
    public CreationClassName createCreationClassName() {
        return new CreationClassName();
    }


    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }


    /**
     * Create an instance of {@link IPVersionSupport }
     * 
     */
    public IPVersionSupport createIPVersionSupport() {
        return new IPVersionSupport();
    }


    /**
     * Create an instance of {@link OtherTypeDescription }
     * 
     */
    public OtherTypeDescription createOtherTypeDescription() {
        return new OtherTypeDescription();
    }


    /**
     * Create an instance of {@link CimByte }
     * 
     */
    public CimByte createCimByte() {
        return new CimByte();
    }


    /**
     * Create an instance of {@link Caption }
     * 
     */
    public Caption createCaption() {
        return new Caption();
    }


    /**
     * Create an instance of {@link AddressOrigin }
     * 
     */
    public AddressOrigin createAddressOrigin() {
        return new AddressOrigin();
    }


    /**
     * Create an instance of {@link CimBase64Binary }
     * 
     */
    public CimBase64Binary createCimBase64Binary() {
        return new CimBase64Binary();
    }


    /**
     * Create an instance of {@link CimReference }
     * 
     */
    public CimReference createCimReference() {
        return new CimReference();
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "IPv4Address")
    public JAXBElement<CimString> createIPv4Address(CimString value) {
        return new JAXBElement<CimString>(_IPv4Address_QNAME, CimString.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimUnsignedShort }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "IPv6SubnetPrefixLength")
    public JAXBElement<CimUnsignedShort> createIPv6SubnetPrefixLength(CimUnsignedShort value) {
        return new JAXBElement<CimUnsignedShort>(_IPv6SubnetPrefixLength_QNAME, CimUnsignedShort.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Caption }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "Caption")
    public JAXBElement<Caption> createCaption(Caption value) {
        return new JAXBElement<Caption>(_Caption_QNAME, Caption.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OtherTypeDescription }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "OtherTypeDescription")
    public JAXBElement<OtherTypeDescription> createOtherTypeDescription(OtherTypeDescription value) {
        return new JAXBElement<OtherTypeDescription>(_OtherTypeDescription_QNAME, OtherTypeDescription.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProtocolIFType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "ProtocolIFType")
    public JAXBElement<ProtocolIFType> createProtocolIFType(ProtocolIFType value) {
        return new JAXBElement<ProtocolIFType>(_ProtocolIFType_QNAME, ProtocolIFType.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommunicationStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "CommunicationStatus")
    public JAXBElement<CommunicationStatus> createCommunicationStatus(CommunicationStatus value) {
        return new JAXBElement<CommunicationStatus>(_CommunicationStatus_QNAME, CommunicationStatus.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "ElementName")
    public JAXBElement<CimString> createElementName(CimString value) {
        return new JAXBElement<CimString>(_ElementName_QNAME, CimString.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransitioningToState }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "TransitioningToState")
    public JAXBElement<TransitioningToState> createTransitioningToState(TransitioningToState value) {
        return new JAXBElement<TransitioningToState>(_TransitioningToState_QNAME, TransitioningToState.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameFormat }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "NameFormat")
    public JAXBElement<NameFormat> createNameFormat(NameFormat value) {
        return new JAXBElement<NameFormat>(_NameFormat_QNAME, NameFormat.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DetailedStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "DetailedStatus")
    public JAXBElement<DetailedStatus> createDetailedStatus(DetailedStatus value) {
        return new JAXBElement<DetailedStatus>(_DetailedStatus_QNAME, DetailedStatus.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IPVersionSupport }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "IPVersionSupport")
    public JAXBElement<IPVersionSupport> createIPVersionSupport(IPVersionSupport value) {
        return new JAXBElement<IPVersionSupport>(_IPVersionSupport_QNAME, IPVersionSupport.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrimaryStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "PrimaryStatus")
    public JAXBElement<PrimaryStatus> createPrimaryStatus(PrimaryStatus value) {
        return new JAXBElement<PrimaryStatus>(_PrimaryStatus_QNAME, PrimaryStatus.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "StatusDescriptions")
    public JAXBElement<CimString> createStatusDescriptions(CimString value) {
        return new JAXBElement<CimString>(_StatusDescriptions_QNAME, CimString.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "Description")
    public JAXBElement<CimString> createDescription(CimString value) {
        return new JAXBElement<CimString>(_Description_QNAME, CimString.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "IPv6Address")
    public JAXBElement<CimString> createIPv6Address(CimString value) {
        return new JAXBElement<CimString>(_IPv6Address_QNAME, CimString.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "OtherEnabledState")
    public JAXBElement<CimString> createOtherEnabledState(CimString value) {
        return new JAXBElement<CimString>(_OtherEnabledState_QNAME, CimString.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OperationalStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "OperationalStatus")
    public JAXBElement<OperationalStatus> createOperationalStatus(OperationalStatus value) {
        return new JAXBElement<OperationalStatus>(_OperationalStatus_QNAME, OperationalStatus.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "InstanceID")
    public JAXBElement<CimString> createInstanceID(CimString value) {
        return new JAXBElement<CimString>(_InstanceID_QNAME, CimString.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProtocolType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "ProtocolType")
    public JAXBElement<ProtocolType> createProtocolType(ProtocolType value) {
        return new JAXBElement<ProtocolType>(_ProtocolType_QNAME, ProtocolType.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnabledDefault }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "EnabledDefault")
    public JAXBElement<EnabledDefault> createEnabledDefault(EnabledDefault value) {
        return new JAXBElement<EnabledDefault>(_EnabledDefault_QNAME, EnabledDefault.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IPv6AddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "IPv6AddressType")
    public JAXBElement<IPv6AddressType> createIPv6AddressType(IPv6AddressType value) {
        return new JAXBElement<IPv6AddressType>(_IPv6AddressType_QNAME, IPv6AddressType.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CIMIPProtocolEndpointType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "CIM_IPProtocolEndpoint")
    public JAXBElement<CIMIPProtocolEndpointType> createCIMIPProtocolEndpoint(CIMIPProtocolEndpointType value) {
        return new JAXBElement<CIMIPProtocolEndpointType>(_CIMIPProtocolEndpoint_QNAME, CIMIPProtocolEndpointType.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HealthState }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "HealthState")
    public JAXBElement<HealthState> createHealthState(HealthState value) {
        return new JAXBElement<HealthState>(_HealthState_QNAME, HealthState.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link com.dell.isg.smi.wsman.command.entity.ipprotocolendpoint.RequestedState }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "RequestedState")
    public JAXBElement<com.dell.isg.smi.wsman.command.entity.ipprotocolendpoint.RequestedState> createRequestedState(com.dell.isg.smi.wsman.command.entity.ipprotocolendpoint.RequestedState value) {
        return new JAXBElement<com.dell.isg.smi.wsman.command.entity.ipprotocolendpoint.RequestedState>(_RequestedState_QNAME, com.dell.isg.smi.wsman.command.entity.ipprotocolendpoint.RequestedState.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "SubnetMask")
    public JAXBElement<CimString> createSubnetMask(CimString value) {
        return new JAXBElement<CimString>(_SubnetMask_QNAME, CimString.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OperatingStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "OperatingStatus")
    public JAXBElement<OperatingStatus> createOperatingStatus(OperatingStatus value) {
        return new JAXBElement<OperatingStatus>(_OperatingStatus_QNAME, OperatingStatus.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimDateTime }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "InstallDate")
    public JAXBElement<CimDateTime> createInstallDate(CimDateTime value) {
        return new JAXBElement<CimDateTime>(_InstallDate_QNAME, CimDateTime.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AvailableRequestedStates }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "AvailableRequestedStates")
    public JAXBElement<AvailableRequestedStates> createAvailableRequestedStates(AvailableRequestedStates value) {
        return new JAXBElement<AvailableRequestedStates>(_AvailableRequestedStates_QNAME, AvailableRequestedStates.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Status }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "Status")
    public JAXBElement<Status> createStatus(Status value) {
        return new JAXBElement<Status>(_Status_QNAME, Status.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressOrigin }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "AddressOrigin")
    public JAXBElement<AddressOrigin> createAddressOrigin(AddressOrigin value) {
        return new JAXBElement<AddressOrigin>(_AddressOrigin_QNAME, AddressOrigin.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "Address")
    public JAXBElement<CimString> createAddress(CimString value) {
        return new JAXBElement<CimString>(_Address_QNAME, CimString.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "AddressType")
    public JAXBElement<AddressType> createAddressType(AddressType value) {
        return new JAXBElement<AddressType>(_AddressType_QNAME, AddressType.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimUnsignedByte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "PrefixLength")
    public JAXBElement<CimUnsignedByte> createPrefixLength(CimUnsignedByte value) {
        return new JAXBElement<CimUnsignedByte>(_PrefixLength_QNAME, CimUnsignedByte.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimDateTime }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "TimeOfLastStateChange")
    public JAXBElement<CimDateTime> createTimeOfLastStateChange(CimDateTime value) {
        return new JAXBElement<CimDateTime>(_TimeOfLastStateChange_QNAME, CimDateTime.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnabledState }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema.omc-project.org/wbem/wscim/1/cim-schema/2/OMC_IPMIIPProtocolEndpoint", name = "EnabledState")
    public JAXBElement<EnabledState> createEnabledState(EnabledState value) {
        return new JAXBElement<EnabledState>(_EnabledState_QNAME, EnabledState.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/common", name = "CIM_DateTime", scope = CimDateTime.class)
    public JAXBElement<String> createCimDateTimeCIMDateTime(String value) {
        return new JAXBElement<String>(_CimDateTimeCIMDateTime_QNAME, String.class, CimDateTime.class, value);
    }

}
