/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.10 at 10:46:37 AM CDT 
//

package com.dell.isg.smi.wsman.command.entity.storage;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the com.dell.pg.spectre.business.inventory.storage package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java representation of XML content can consist of schema
 * derived interfaces and classes representing the binding of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in this
 * class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dell.pg.spectre.business.inventory.storage
     * 
     */
    public ObjectFactory() {
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.TreeStatus }
     * 
     */
    public DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.TreeStatus createDellStorageArrayInfoVirtualDisksDCStorageObjectTreeStatus() {
        return new DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.TreeStatus();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.Layout }
     * 
     */
    public DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.Layout createDellStorageArrayInfoVirtualDisksDCStorageObjectLayout() {
        return new DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.Layout();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.RAIDLevelsMask }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.RAIDLevelsMask createDellStorageArrayInfoControllersDCStorageObjectRAIDLevelsMask() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.RAIDLevelsMask();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.MediaType }
     * 
     */
    public DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.MediaType createDellStorageArrayInfoVirtualDisksDCStorageObjectMediaType() {
        return new DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.MediaType();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Batteries.DCStorageObject.BatteryCapacityState }
     * 
     */
    public DellStorage.ArrayInfo.Batteries.DCStorageObject.BatteryCapacityState createDellStorageArrayInfoBatteriesDCStorageObjectBatteryCapacityState() {
        return new DellStorage.ArrayInfo.Batteries.DCStorageObject.BatteryCapacityState();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.CurrentMethodMask }
     * 
     */
    public DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.CurrentMethodMask createDellStorageArrayInfoVirtualDisksDCStorageObjectCurrentMethodMask() {
        return new DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.CurrentMethodMask();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Enclosures.DCStorageObject.Channel }
     * 
     */
    public DellStorage.ArrayInfo.Enclosures.DCStorageObject.Channel createDellStorageArrayInfoEnclosuresDCStorageObjectChannel() {
        return new DellStorage.ArrayInfo.Enclosures.DCStorageObject.Channel();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.ObjStatus }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.ObjStatus createDellStorageArrayInfoControllersDCStorageObjectObjStatus() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.ObjStatus();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxDrivesForRAID1 }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxDrivesForRAID1 createDellStorageArrayInfoControllersDCStorageObjectMaxDrivesForRAID1() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxDrivesForRAID1();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxVDAllowed }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxVDAllowed createDellStorageArrayInfoControllersDCStorageObjectMaxVDAllowed() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxVDAllowed();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ManufactureDay }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ManufactureDay createDellStorageArrayInfoArrayDisksDCStorageObjectManufactureDay() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ManufactureDay();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.GetcapsGroup }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.GetcapsGroup createDellStorageArrayInfoArrayDisksDCStorageObjectGetcapsGroup() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.GetcapsGroup();
    }


    /**
     * Create an instance of {@link DellStorage }
     * 
     */
    public DellStorage createDellStorage() {
        return new DellStorage();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxDrivesForRAID0 }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxDrivesForRAID0 createDellStorageArrayInfoControllersDCStorageObjectMaxDrivesForRAID0() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxDrivesForRAID0();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Enclosures.DCStorageObject.ObjType }
     * 
     */
    public DellStorage.ArrayInfo.Enclosures.DCStorageObject.ObjType createDellStorageArrayInfoEnclosuresDCStorageObjectObjType() {
        return new DellStorage.ArrayInfo.Enclosures.DCStorageObject.ObjType();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.PartNo }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.PartNo createDellStorageArrayInfoArrayDisksDCStorageObjectPartNo() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.PartNo();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.ControllerModelNumber }
     * 
     */
    public DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.ControllerModelNumber createDellStorageArrayInfoVirtualDisksDCStorageObjectControllerModelNumber() {
        return new DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.ControllerModelNumber();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.ObjType }
     * 
     */
    public DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.ObjType createDellStorageArrayInfoVirtualDisksDCStorageObjectObjType() {
        return new DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.ObjType();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.TreeStatus }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.TreeStatus createDellStorageArrayInfoControllersDCStorageObjectTreeStatus() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.TreeStatus();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ObjStatus }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ObjStatus createDellStorageArrayInfoArrayDisksDCStorageObjectObjStatus() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ObjStatus();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.AttributesMask }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.AttributesMask createDellStorageArrayInfoArrayDisksDCStorageObjectAttributesMask() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.AttributesMask();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Batteries.DCStorageObject.ControllerNum }
     * 
     */
    public DellStorage.ArrayInfo.Batteries.DCStorageObject.ControllerNum createDellStorageArrayInfoBatteriesDCStorageObjectControllerNum() {
        return new DellStorage.ArrayInfo.Batteries.DCStorageObject.ControllerNum();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers }
     * 
     */
    public DellStorage.ArrayInfo.Controllers createDellStorageArrayInfoControllers() {
        return new DellStorage.ArrayInfo.Controllers();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.FreeSpace }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.FreeSpace createDellStorageArrayInfoArrayDisksDCStorageObjectFreeSpace() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.FreeSpace();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.Name }
     * 
     */
    public DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.Name createDellStorageArrayInfoVirtualDisksDCStorageObjectName() {
        return new DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.Name();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxOsLimitForLogicalDriveSize }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxOsLimitForLogicalDriveSize createDellStorageArrayInfoControllersDCStorageObjectMaxOsLimitForLogicalDriveSize() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxOsLimitForLogicalDriveSize();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.PatrolReadMode }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.PatrolReadMode createDellStorageArrayInfoControllersDCStorageObjectPatrolReadMode() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.PatrolReadMode();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxNameLength }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxNameLength createDellStorageArrayInfoControllersDCStorageObjectMaxNameLength() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxNameLength();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Enclosures.DCStorageObject.ProductVersion }
     * 
     */
    public DellStorage.ArrayInfo.Enclosures.DCStorageObject.ProductVersion createDellStorageArrayInfoEnclosuresDCStorageObjectProductVersion() {
        return new DellStorage.ArrayInfo.Enclosures.DCStorageObject.ProductVersion();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ProductID }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ProductID createDellStorageArrayInfoArrayDisksDCStorageObjectProductID() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ProductID();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks createDellStorageArrayInfoArrayDisks() {
        return new DellStorage.ArrayInfo.ArrayDisks();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject createDellStorageArrayInfoControllersDCStorageObject() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.DeviceID }
     * 
     */
    public DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.DeviceID createDellStorageArrayInfoVirtualDisksDCStorageObjectDeviceID() {
        return new DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.DeviceID();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.MasterMethodMask }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.MasterMethodMask createDellStorageArrayInfoArrayDisksDCStorageObjectMasterMethodMask() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.MasterMethodMask();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.SSDMixandSSDHDDMixinVD }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.SSDMixandSSDHDDMixinVD createDellStorageArrayInfoControllersDCStorageObjectSSDMixandSSDHDDMixinVD() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.SSDMixandSSDHDDMixinVD();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Batteries.DCStorageObject.Nexus }
     * 
     */
    public DellStorage.ArrayInfo.Batteries.DCStorageObject.Nexus createDellStorageArrayInfoBatteriesDCStorageObjectNexus() {
        return new DellStorage.ArrayInfo.Batteries.DCStorageObject.Nexus();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.DefaultWritePolicy }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.DefaultWritePolicy createDellStorageArrayInfoControllersDCStorageObjectDefaultWritePolicy() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.DefaultWritePolicy();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.RebuildRate }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.RebuildRate createDellStorageArrayInfoControllersDCStorageObjectRebuildRate() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.RebuildRate();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ControllerModelNumber }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ControllerModelNumber createDellStorageArrayInfoArrayDisksDCStorageObjectControllerModelNumber() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ControllerModelNumber();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.VendorID }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.VendorID createDellStorageArrayInfoControllersDCStorageObjectVendorID() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.VendorID();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ContiguousFree }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ContiguousFree createDellStorageArrayInfoArrayDisksDCStorageObjectContiguousFree() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ContiguousFree();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo }
     * 
     */
    public DellStorage.ArrayInfo createDellStorageArrayInfo() {
        return new DellStorage.ArrayInfo();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Batteries.DCStorageObject.ControllerModelNumber }
     * 
     */
    public DellStorage.ArrayInfo.Batteries.DCStorageObject.ControllerModelNumber createDellStorageArrayInfoBatteriesDCStorageObjectControllerModelNumber() {
        return new DellStorage.ArrayInfo.Batteries.DCStorageObject.ControllerModelNumber();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.PciID }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.PciID createDellStorageArrayInfoControllersDCStorageObjectPciID() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.PciID();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.MasterMethodMask }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.MasterMethodMask createDellStorageArrayInfoControllersDCStorageObjectMasterMethodMask() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.MasterMethodMask();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.Channels }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.Channels createDellStorageArrayInfoControllersDCStorageObjectChannels() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.Channels();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.MediaType }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.MediaType createDellStorageArrayInfoArrayDisksDCStorageObjectMediaType() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.MediaType();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Channels.DCStorageObject.MasterMethodMask }
     * 
     */
    public DellStorage.ArrayInfo.Channels.DCStorageObject.MasterMethodMask createDellStorageArrayInfoChannelsDCStorageObjectMasterMethodMask() {
        return new DellStorage.ArrayInfo.Channels.DCStorageObject.MasterMethodMask();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Batteries.DCStorageObject.ObjID }
     * 
     */
    public DellStorage.ArrayInfo.Batteries.DCStorageObject.ObjID createDellStorageArrayInfoBatteriesDCStorageObjectObjID() {
        return new DellStorage.ArrayInfo.Batteries.DCStorageObject.ObjID();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.ObjType }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.ObjType createDellStorageArrayInfoControllersDCStorageObjectObjType() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.ObjType();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxDrivesForRAID60 }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxDrivesForRAID60 createDellStorageArrayInfoControllersDCStorageObjectMaxDrivesForRAID60() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxDrivesForRAID60();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Batteries.DCStorageObject.BatteryID }
     * 
     */
    public DellStorage.ArrayInfo.Batteries.DCStorageObject.BatteryID createDellStorageArrayInfoBatteriesDCStorageObjectBatteryID() {
        return new DellStorage.ArrayInfo.Batteries.DCStorageObject.BatteryID();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Channels.DCStorageObject.BusProtocol }
     * 
     */
    public DellStorage.ArrayInfo.Channels.DCStorageObject.BusProtocol createDellStorageArrayInfoChannelsDCStorageObjectBusProtocol() {
        return new DellStorage.ArrayInfo.Channels.DCStorageObject.BusProtocol();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.AttributesMask }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.AttributesMask createDellStorageArrayInfoControllersDCStorageObjectAttributesMask() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.AttributesMask();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.Length }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.Length createDellStorageArrayInfoArrayDisksDCStorageObjectLength() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.Length();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.ControllerNum }
     * 
     */
    public DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.ControllerNum createDellStorageArrayInfoVirtualDisksDCStorageObjectControllerNum() {
        return new DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.ControllerNum();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.GlobalNo }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.GlobalNo createDellStorageArrayInfoArrayDisksDCStorageObjectGlobalNo() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.GlobalNo();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.EnclosureIndex }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.EnclosureIndex createDellStorageArrayInfoArrayDisksDCStorageObjectEnclosureIndex() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.EnclosureIndex();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.MasterMethodMask }
     * 
     */
    public DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.MasterMethodMask createDellStorageArrayInfoVirtualDisksDCStorageObjectMasterMethodMask() {
        return new DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.MasterMethodMask();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Enclosures.DCStorageObject.BusProtocol }
     * 
     */
    public DellStorage.ArrayInfo.Enclosures.DCStorageObject.BusProtocol createDellStorageArrayInfoEnclosuresDCStorageObjectBusProtocol() {
        return new DellStorage.ArrayInfo.Enclosures.DCStorageObject.BusProtocol();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Enclosures.DCStorageObject.MasterMethodMask }
     * 
     */
    public DellStorage.ArrayInfo.Enclosures.DCStorageObject.MasterMethodMask createDellStorageArrayInfoEnclosuresDCStorageObjectMasterMethodMask() {
        return new DellStorage.ArrayInfo.Enclosures.DCStorageObject.MasterMethodMask();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.GlobalNo }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.GlobalNo createDellStorageArrayInfoControllersDCStorageObjectGlobalNo() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.GlobalNo();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.DiskCachePolicy }
     * 
     */
    public DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.DiskCachePolicy createDellStorageArrayInfoVirtualDisksDCStorageObjectDiskCachePolicy() {
        return new DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.DiskCachePolicy();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxNumOfSpans }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxNumOfSpans createDellStorageArrayInfoControllersDCStorageObjectMaxNumOfSpans() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxNumOfSpans();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.NumOfPartition }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.NumOfPartition createDellStorageArrayInfoArrayDisksDCStorageObjectNumOfPartition() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.NumOfPartition();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.AbortCheckConsistencyOnError }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.AbortCheckConsistencyOnError createDellStorageArrayInfoControllersDCStorageObjectAbortCheckConsistencyOnError() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.AbortCheckConsistencyOnError();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Enclosures }
     * 
     */
    public DellStorage.ArrayInfo.Enclosures createDellStorageArrayInfoEnclosures() {
        return new DellStorage.ArrayInfo.Enclosures();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Channels }
     * 
     */
    public DellStorage.ArrayInfo.Channels createDellStorageArrayInfoChannels() {
        return new DellStorage.ArrayInfo.Channels();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Enclosures.DCStorageObject.GlobalNo }
     * 
     */
    public DellStorage.ArrayInfo.Enclosures.DCStorageObject.GlobalNo createDellStorageArrayInfoEnclosuresDCStorageObjectGlobalNo() {
        return new DellStorage.ArrayInfo.Enclosures.DCStorageObject.GlobalNo();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.MinDrivesForRAID6 }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.MinDrivesForRAID6 createDellStorageArrayInfoControllersDCStorageObjectMinDrivesForRAID6() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.MinDrivesForRAID6();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Batteries.DCStorageObject.ObjType }
     * 
     */
    public DellStorage.ArrayInfo.Batteries.DCStorageObject.ObjType createDellStorageArrayInfoBatteriesDCStorageObjectObjType() {
        return new DellStorage.ArrayInfo.Batteries.DCStorageObject.ObjType();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.LogicalDriveNum }
     * 
     */
    public DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.LogicalDriveNum createDellStorageArrayInfoVirtualDisksDCStorageObjectLogicalDriveNum() {
        return new DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.LogicalDriveNum();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Enclosures.DCStorageObject.VendorID }
     * 
     */
    public DellStorage.ArrayInfo.Enclosures.DCStorageObject.VendorID createDellStorageArrayInfoEnclosuresDCStorageObjectVendorID() {
        return new DellStorage.ArrayInfo.Enclosures.DCStorageObject.VendorID();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.RequiredFirmwareVersion }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.RequiredFirmwareVersion createDellStorageArrayInfoControllersDCStorageObjectRequiredFirmwareVersion() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.RequiredFirmwareVersion();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ControllerNum }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ControllerNum createDellStorageArrayInfoArrayDisksDCStorageObjectControllerNum() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ControllerNum();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxDrivesForRAID50 }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxDrivesForRAID50 createDellStorageArrayInfoControllersDCStorageObjectMaxDrivesForRAID50() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxDrivesForRAID50();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.Vendor }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.Vendor createDellStorageArrayInfoArrayDisksDCStorageObjectVendor() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.Vendor();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.DiskProductVendor }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.DiskProductVendor createDellStorageArrayInfoArrayDisksDCStorageObjectDiskProductVendor() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.DiskProductVendor();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxNumOfDisksInSpan }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxNumOfDisksInSpan createDellStorageArrayInfoControllersDCStorageObjectMaxNumOfDisksInSpan() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxNumOfDisksInSpan();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxDrivesForRAID5 }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxDrivesForRAID5 createDellStorageArrayInfoControllersDCStorageObjectMaxDrivesForRAID5() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxDrivesForRAID5();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Enclosures.DCStorageObject.EnclosureIndex }
     * 
     */
    public DellStorage.ArrayInfo.Enclosures.DCStorageObject.EnclosureIndex createDellStorageArrayInfoEnclosuresDCStorageObjectEnclosureIndex() {
        return new DellStorage.ArrayInfo.Enclosures.DCStorageObject.EnclosureIndex();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.ReconstructRate }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.ReconstructRate createDellStorageArrayInfoControllersDCStorageObjectReconstructRate() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.ReconstructRate();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.TargetID }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.TargetID createDellStorageArrayInfoArrayDisksDCStorageObjectTargetID() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.TargetID();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ManufactureYear }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ManufactureYear createDellStorageArrayInfoArrayDisksDCStorageObjectManufactureYear() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ManufactureYear();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.CurrentMethodMask }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.CurrentMethodMask createDellStorageArrayInfoControllersDCStorageObjectCurrentMethodMask() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.CurrentMethodMask();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.CtrlMaxEnclosuresChained }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.CtrlMaxEnclosuresChained createDellStorageArrayInfoControllersDCStorageObjectCtrlMaxEnclosuresChained() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.CtrlMaxEnclosuresChained();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.PCIFunctionNum }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.PCIFunctionNum createDellStorageArrayInfoControllersDCStorageObjectPCIFunctionNum() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.PCIFunctionNum();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Batteries.DCStorageObject.NextLearnCycleTime }
     * 
     */
    public DellStorage.ArrayInfo.Batteries.DCStorageObject.NextLearnCycleTime createDellStorageArrayInfoBatteriesDCStorageObjectNextLearnCycleTime() {
        return new DellStorage.ArrayInfo.Batteries.DCStorageObject.NextLearnCycleTime();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Enclosures.DCStorageObject.TreeStatus }
     * 
     */
    public DellStorage.ArrayInfo.Enclosures.DCStorageObject.TreeStatus createDellStorageArrayInfoEnclosuresDCStorageObjectTreeStatus() {
        return new DellStorage.ArrayInfo.Enclosures.DCStorageObject.TreeStatus();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Batteries.DCStorageObject.GlobalNo }
     * 
     */
    public DellStorage.ArrayInfo.Batteries.DCStorageObject.GlobalNo createDellStorageArrayInfoBatteriesDCStorageObjectGlobalNo() {
        return new DellStorage.ArrayInfo.Batteries.DCStorageObject.GlobalNo();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.BusProtocol }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.BusProtocol createDellStorageArrayInfoControllersDCStorageObjectBusProtocol() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.BusProtocol();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.Nexus }
     * 
     */
    public DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.Nexus createDellStorageArrayInfoVirtualDisksDCStorageObjectNexus() {
        return new DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.Nexus();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.Length }
     * 
     */
    public DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.Length createDellStorageArrayInfoVirtualDisksDCStorageObjectLength() {
        return new DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.Length();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.MinDrivesForRAID60 }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.MinDrivesForRAID60 createDellStorageArrayInfoControllersDCStorageObjectMinDrivesForRAID60() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.MinDrivesForRAID60();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Channels.DCStorageObject.ControllerNum }
     * 
     */
    public DellStorage.ArrayInfo.Channels.DCStorageObject.ControllerNum createDellStorageArrayInfoChannelsDCStorageObjectControllerNum() {
        return new DellStorage.ArrayInfo.Channels.DCStorageObject.ControllerNum();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.StripeSizesMask }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.StripeSizesMask createDellStorageArrayInfoControllersDCStorageObjectStripeSizesMask() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.StripeSizesMask();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.GlobalNo }
     * 
     */
    public DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.GlobalNo createDellStorageArrayInfoVirtualDisksDCStorageObjectGlobalNo() {
        return new DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.GlobalNo();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.PCIDeviceNum }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.PCIDeviceNum createDellStorageArrayInfoControllersDCStorageObjectPCIDeviceNum() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.PCIDeviceNum();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Batteries.DCStorageObject.ObjState }
     * 
     */
    public DellStorage.ArrayInfo.Batteries.DCStorageObject.ObjState createDellStorageArrayInfoBatteriesDCStorageObjectObjState() {
        return new DellStorage.ArrayInfo.Batteries.DCStorageObject.ObjState();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Batteries.DCStorageObject.MaxLearnDelay }
     * 
     */
    public DellStorage.ArrayInfo.Batteries.DCStorageObject.MaxLearnDelay createDellStorageArrayInfoBatteriesDCStorageObjectMaxLearnDelay() {
        return new DellStorage.ArrayInfo.Batteries.DCStorageObject.MaxLearnDelay();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.PCISlot }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.PCISlot createDellStorageArrayInfoControllersDCStorageObjectPCISlot() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.PCISlot();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.VirtualDisks }
     * 
     */
    public DellStorage.ArrayInfo.VirtualDisks createDellStorageArrayInfoVirtualDisks() {
        return new DellStorage.ArrayInfo.VirtualDisks();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.SASAddress }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.SASAddress createDellStorageArrayInfoArrayDisksDCStorageObjectSASAddress() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.SASAddress();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.DefaultReadPolicy }
     * 
     */
    public DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.DefaultReadPolicy createDellStorageArrayInfoVirtualDisksDCStorageObjectDefaultReadPolicy() {
        return new DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.DefaultReadPolicy();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Batteries.DCStorageObject }
     * 
     */
    public DellStorage.ArrayInfo.Batteries.DCStorageObject createDellStorageArrayInfoBatteriesDCStorageObject() {
        return new DellStorage.ArrayInfo.Batteries.DCStorageObject();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.TreeStatus }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.TreeStatus createDellStorageArrayInfoArrayDisksDCStorageObjectTreeStatus() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.TreeStatus();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Batteries }
     * 
     */
    public DellStorage.ArrayInfo.Batteries createDellStorageArrayInfoBatteries() {
        return new DellStorage.ArrayInfo.Batteries();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.ObjID }
     * 
     */
    public DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.ObjID createDellStorageArrayInfoVirtualDisksDCStorageObjectObjID() {
        return new DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.ObjID();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.ControllerModelNumber }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.ControllerModelNumber createDellStorageArrayInfoControllersDCStorageObjectControllerModelNumber() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.ControllerModelNumber();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.EnclosureID }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.EnclosureID createDellStorageArrayInfoArrayDisksDCStorageObjectEnclosureID() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.EnclosureID();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Enclosures.DCStorageObject.ProductID }
     * 
     */
    public DellStorage.ArrayInfo.Enclosures.DCStorageObject.ProductID createDellStorageArrayInfoEnclosuresDCStorageObjectProductID() {
        return new DellStorage.ArrayInfo.Enclosures.DCStorageObject.ProductID();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.StripeSizeForRaidLevelMask }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.StripeSizeForRaidLevelMask createDellStorageArrayInfoControllersDCStorageObjectStripeSizeForRaidLevelMask() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.StripeSizeForRaidLevelMask();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.Revision }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.Revision createDellStorageArrayInfoArrayDisksDCStorageObjectRevision() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.Revision();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.ObjStatus }
     * 
     */
    public DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.ObjStatus createDellStorageArrayInfoVirtualDisksDCStorageObjectObjStatus() {
        return new DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.ObjStatus();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxDrivesForRAID10 }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxDrivesForRAID10 createDellStorageArrayInfoControllersDCStorageObjectMaxDrivesForRAID10() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxDrivesForRAID10();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.ObjState }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.ObjState createDellStorageArrayInfoControllersDCStorageObjectObjState() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.ObjState();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ArrayNum }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ArrayNum createDellStorageArrayInfoArrayDisksDCStorageObjectArrayNum() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ArrayNum();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.MinDrivesForRAID1E }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.MinDrivesForRAID1E createDellStorageArrayInfoControllersDCStorageObjectMinDrivesForRAID1E() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.MinDrivesForRAID1E();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.PersistentHotSlot }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.PersistentHotSlot createDellStorageArrayInfoControllersDCStorageObjectPersistentHotSlot() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.PersistentHotSlot();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Channels.DCStorageObject.CurrentMethodMask }
     * 
     */
    public DellStorage.ArrayInfo.Channels.DCStorageObject.CurrentMethodMask createDellStorageArrayInfoChannelsDCStorageObjectCurrentMethodMask() {
        return new DellStorage.ArrayInfo.Channels.DCStorageObject.CurrentMethodMask();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxDrivesForRAID1E }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxDrivesForRAID1E createDellStorageArrayInfoControllersDCStorageObjectMaxDrivesForRAID1E() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxDrivesForRAID1E();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.SasAddress }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.SasAddress createDellStorageArrayInfoControllersDCStorageObjectSasAddress() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.SasAddress();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.PatrolReadModeMask }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.PatrolReadModeMask createDellStorageArrayInfoControllersDCStorageObjectPatrolReadModeMask() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.PatrolReadModeMask();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Enclosures.DCStorageObject.ControllerNum }
     * 
     */
    public DellStorage.ArrayInfo.Enclosures.DCStorageObject.ControllerNum createDellStorageArrayInfoEnclosuresDCStorageObjectControllerNum() {
        return new DellStorage.ArrayInfo.Enclosures.DCStorageObject.ControllerNum();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.VirtualDisks.DCStorageObject }
     * 
     */
    public DellStorage.ArrayInfo.VirtualDisks.DCStorageObject createDellStorageArrayInfoVirtualDisksDCStorageObject() {
        return new DellStorage.ArrayInfo.VirtualDisks.DCStorageObject();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Enclosures.DCStorageObject.DeviceID }
     * 
     */
    public DellStorage.ArrayInfo.Enclosures.DCStorageObject.DeviceID createDellStorageArrayInfoEnclosuresDCStorageObjectDeviceID() {
        return new DellStorage.ArrayInfo.Enclosures.DCStorageObject.DeviceID();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Channels.DCStorageObject.ObjID }
     * 
     */
    public DellStorage.ArrayInfo.Channels.DCStorageObject.ObjID createDellStorageArrayInfoChannelsDCStorageObjectObjID() {
        return new DellStorage.ArrayInfo.Channels.DCStorageObject.ObjID();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.PatrolReadIterations }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.PatrolReadIterations createDellStorageArrayInfoControllersDCStorageObjectPatrolReadIterations() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.PatrolReadIterations();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Channels.DCStorageObject.ObjState }
     * 
     */
    public DellStorage.ArrayInfo.Channels.DCStorageObject.ObjState createDellStorageArrayInfoChannelsDCStorageObjectObjState() {
        return new DellStorage.ArrayInfo.Channels.DCStorageObject.ObjState();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.DefaultWritePolicy }
     * 
     */
    public DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.DefaultWritePolicy createDellStorageArrayInfoVirtualDisksDCStorageObjectDefaultWritePolicy() {
        return new DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.DefaultWritePolicy();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.CheckConsistencyRate }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.CheckConsistencyRate createDellStorageArrayInfoControllersDCStorageObjectCheckConsistencyRate() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.CheckConsistencyRate();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxSpans }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxSpans createDellStorageArrayInfoControllersDCStorageObjectMaxSpans() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxSpans();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.Channel }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.Channel createDellStorageArrayInfoArrayDisksDCStorageObjectChannel() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.Channel();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.AutoCopybackOnPredictiveFailure }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.AutoCopybackOnPredictiveFailure createDellStorageArrayInfoControllersDCStorageObjectAutoCopybackOnPredictiveFailure() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.AutoCopybackOnPredictiveFailure();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.MinDrivesForRAID50 }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.MinDrivesForRAID50 createDellStorageArrayInfoControllersDCStorageObjectMinDrivesForRAID50() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.MinDrivesForRAID50();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ObjID }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ObjID createDellStorageArrayInfoArrayDisksDCStorageObjectObjID() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ObjID();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject createDellStorageArrayInfoArrayDisksDCStorageObject() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Channels.DCStorageObject.ObjStatus }
     * 
     */
    public DellStorage.ArrayInfo.Channels.DCStorageObject.ObjStatus createDellStorageArrayInfoChannelsDCStorageObjectObjStatus() {
        return new DellStorage.ArrayInfo.Channels.DCStorageObject.ObjStatus();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ObjState }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ObjState createDellStorageArrayInfoArrayDisksDCStorageObjectObjState() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ObjState();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Batteries.DCStorageObject.VendorID }
     * 
     */
    public DellStorage.ArrayInfo.Batteries.DCStorageObject.VendorID createDellStorageArrayInfoBatteriesDCStorageObjectVendorID() {
        return new DellStorage.ArrayInfo.Batteries.DCStorageObject.VendorID();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Batteries.DCStorageObject.CurrentMethodMask }
     * 
     */
    public DellStorage.ArrayInfo.Batteries.DCStorageObject.CurrentMethodMask createDellStorageArrayInfoBatteriesDCStorageObjectCurrentMethodMask() {
        return new DellStorage.ArrayInfo.Batteries.DCStorageObject.CurrentMethodMask();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Batteries.DCStorageObject.BatteryLearnState }
     * 
     */
    public DellStorage.ArrayInfo.Batteries.DCStorageObject.BatteryLearnState createDellStorageArrayInfoBatteriesDCStorageObjectBatteryLearnState() {
        return new DellStorage.ArrayInfo.Batteries.DCStorageObject.BatteryLearnState();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Enclosures.DCStorageObject.FirmwareVer }
     * 
     */
    public DellStorage.ArrayInfo.Enclosures.DCStorageObject.FirmwareVer createDellStorageArrayInfoEnclosuresDCStorageObjectFirmwareVer() {
        return new DellStorage.ArrayInfo.Enclosures.DCStorageObject.FirmwareVer();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Enclosures.DCStorageObject.CurrentMethodMask }
     * 
     */
    public DellStorage.ArrayInfo.Enclosures.DCStorageObject.CurrentMethodMask createDellStorageArrayInfoEnclosuresDCStorageObjectCurrentMethodMask() {
        return new DellStorage.ArrayInfo.Enclosures.DCStorageObject.CurrentMethodMask();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.ReadPolicy }
     * 
     */
    public DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.ReadPolicy createDellStorageArrayInfoVirtualDisksDCStorageObjectReadPolicy() {
        return new DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.ReadPolicy();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.MinDrivesForRAID1 }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.MinDrivesForRAID1 createDellStorageArrayInfoControllersDCStorageObjectMinDrivesForRAID1() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.MinDrivesForRAID1();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.ObjState }
     * 
     */
    public DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.ObjState createDellStorageArrayInfoVirtualDisksDCStorageObjectObjState() {
        return new DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.ObjState();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Channels.DCStorageObject.TreeStatus }
     * 
     */
    public DellStorage.ArrayInfo.Channels.DCStorageObject.TreeStatus createDellStorageArrayInfoChannelsDCStorageObjectTreeStatus() {
        return new DellStorage.ArrayInfo.Channels.DCStorageObject.TreeStatus();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.VendorID }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.VendorID createDellStorageArrayInfoArrayDisksDCStorageObjectVendorID() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.VendorID();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Enclosures.DCStorageObject.MaxNumOfPDSlots }
     * 
     */
    public DellStorage.ArrayInfo.Enclosures.DCStorageObject.MaxNumOfPDSlots createDellStorageArrayInfoEnclosuresDCStorageObjectMaxNumOfPDSlots() {
        return new DellStorage.ArrayInfo.Enclosures.DCStorageObject.MaxNumOfPDSlots();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.CtrlMaxCreateDiskSize }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.CtrlMaxCreateDiskSize createDellStorageArrayInfoControllersDCStorageObjectCtrlMaxCreateDiskSize() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.CtrlMaxCreateDiskSize();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.BusProtocol }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.BusProtocol createDellStorageArrayInfoArrayDisksDCStorageObjectBusProtocol() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.BusProtocol();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Enclosures.DCStorageObject.ObjID }
     * 
     */
    public DellStorage.ArrayInfo.Enclosures.DCStorageObject.ObjID createDellStorageArrayInfoEnclosuresDCStorageObjectObjID() {
        return new DellStorage.ArrayInfo.Enclosures.DCStorageObject.ObjID();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.ReadPolicyMask }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.ReadPolicyMask createDellStorageArrayInfoControllersDCStorageObjectReadPolicyMask() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.ReadPolicyMask();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ManufactureWeek }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ManufactureWeek createDellStorageArrayInfoArrayDisksDCStorageObjectManufactureWeek() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ManufactureWeek();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Batteries.DCStorageObject.ObjStatus }
     * 
     */
    public DellStorage.ArrayInfo.Batteries.DCStorageObject.ObjStatus createDellStorageArrayInfoBatteriesDCStorageObjectObjStatus() {
        return new DellStorage.ArrayInfo.Batteries.DCStorageObject.ObjStatus();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Channels.DCStorageObject.VendorID }
     * 
     */
    public DellStorage.ArrayInfo.Channels.DCStorageObject.VendorID createDellStorageArrayInfoChannelsDCStorageObjectVendorID() {
        return new DellStorage.ArrayInfo.Channels.DCStorageObject.VendorID();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.ChangeControllerPropertyMask }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.ChangeControllerPropertyMask createDellStorageArrayInfoControllersDCStorageObjectChangeControllerPropertyMask() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.ChangeControllerPropertyMask();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.PatrolReadRate }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.PatrolReadRate createDellStorageArrayInfoControllersDCStorageObjectPatrolReadRate() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.PatrolReadRate();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.CurrentDriverVersion }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.CurrentDriverVersion createDellStorageArrayInfoControllersDCStorageObjectCurrentDriverVersion() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.CurrentDriverVersion();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.UseFullDiskSizeMask }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.UseFullDiskSizeMask createDellStorageArrayInfoControllersDCStorageObjectUseFullDiskSizeMask() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.UseFullDiskSizeMask();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.DeviceName }
     * 
     */
    public DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.DeviceName createDellStorageArrayInfoVirtualDisksDCStorageObjectDeviceName() {
        return new DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.DeviceName();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Enclosures.DCStorageObject.EnclosureType }
     * 
     */
    public DellStorage.ArrayInfo.Enclosures.DCStorageObject.EnclosureType createDellStorageArrayInfoEnclosuresDCStorageObjectEnclosureType() {
        return new DellStorage.ArrayInfo.Enclosures.DCStorageObject.EnclosureType();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.NumOfAssociatedVD }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.NumOfAssociatedVD createDellStorageArrayInfoArrayDisksDCStorageObjectNumOfAssociatedVD() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.NumOfAssociatedVD();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Enclosures.DCStorageObject.SASAddress }
     * 
     */
    public DellStorage.ArrayInfo.Enclosures.DCStorageObject.SASAddress createDellStorageArrayInfoEnclosuresDCStorageObjectSASAddress() {
        return new DellStorage.ArrayInfo.Enclosures.DCStorageObject.SASAddress();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Enclosures.DCStorageObject }
     * 
     */
    public DellStorage.ArrayInfo.Enclosures.DCStorageObject createDellStorageArrayInfoEnclosuresDCStorageObject() {
        return new DellStorage.ArrayInfo.Enclosures.DCStorageObject();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.UsedSpace }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.UsedSpace createDellStorageArrayInfoArrayDisksDCStorageObjectUsedSpace() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.UsedSpace();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Enclosures.DCStorageObject.ObjState }
     * 
     */
    public DellStorage.ArrayInfo.Enclosures.DCStorageObject.ObjState createDellStorageArrayInfoEnclosuresDCStorageObjectObjState() {
        return new DellStorage.ArrayInfo.Enclosures.DCStorageObject.ObjState();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ArraySize }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ArraySize createDellStorageArrayInfoArrayDisksDCStorageObjectArraySize() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ArraySize();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.BGIRate }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.BGIRate createDellStorageArrayInfoControllersDCStorageObjectBGIRate() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.BGIRate();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Channels.DCStorageObject.ObjType }
     * 
     */
    public DellStorage.ArrayInfo.Channels.DCStorageObject.ObjType createDellStorageArrayInfoChannelsDCStorageObjectObjType() {
        return new DellStorage.ArrayInfo.Channels.DCStorageObject.ObjType();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Channels.DCStorageObject.AttributesMask }
     * 
     */
    public DellStorage.ArrayInfo.Channels.DCStorageObject.AttributesMask createDellStorageArrayInfoChannelsDCStorageObjectAttributesMask() {
        return new DellStorage.ArrayInfo.Channels.DCStorageObject.AttributesMask();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.WritePolicy }
     * 
     */
    public DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.WritePolicy createDellStorageArrayInfoVirtualDisksDCStorageObjectWritePolicy() {
        return new DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.WritePolicy();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Batteries.DCStorageObject.LearnMode }
     * 
     */
    public DellStorage.ArrayInfo.Batteries.DCStorageObject.LearnMode createDellStorageArrayInfoBatteriesDCStorageObjectLearnMode() {
        return new DellStorage.ArrayInfo.Batteries.DCStorageObject.LearnMode();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Enclosures.DCStorageObject.ServiceTag }
     * 
     */
    public DellStorage.ArrayInfo.Enclosures.DCStorageObject.ServiceTag createDellStorageArrayInfoEnclosuresDCStorageObjectServiceTag() {
        return new DellStorage.ArrayInfo.Enclosures.DCStorageObject.ServiceTag();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Enclosures.DCStorageObject.Nexus }
     * 
     */
    public DellStorage.ArrayInfo.Enclosures.DCStorageObject.Nexus createDellStorageArrayInfoEnclosuresDCStorageObjectNexus() {
        return new DellStorage.ArrayInfo.Enclosures.DCStorageObject.Nexus();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.AttributesMask }
     * 
     */
    public DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.AttributesMask createDellStorageArrayInfoVirtualDisksDCStorageObjectAttributesMask() {
        return new DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.AttributesMask();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.MinDrivesForRAID5 }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.MinDrivesForRAID5 createDellStorageArrayInfoControllersDCStorageObjectMinDrivesForRAID5() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.MinDrivesForRAID5();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Channels.DCStorageObject }
     * 
     */
    public DellStorage.ArrayInfo.Channels.DCStorageObject createDellStorageArrayInfoChannelsDCStorageObject() {
        return new DellStorage.ArrayInfo.Channels.DCStorageObject();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Channels.DCStorageObject.GlobalNo }
     * 
     */
    public DellStorage.ArrayInfo.Channels.DCStorageObject.GlobalNo createDellStorageArrayInfoChannelsDCStorageObjectGlobalNo() {
        return new DellStorage.ArrayInfo.Channels.DCStorageObject.GlobalNo();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.BusProtocol }
     * 
     */
    public DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.BusProtocol createDellStorageArrayInfoVirtualDisksDCStorageObjectBusProtocol() {
        return new DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.BusProtocol();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.NumBootPart }
     * 
     */
    public DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.NumBootPart createDellStorageArrayInfoVirtualDisksDCStorageObjectNumBootPart() {
        return new DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.NumBootPart();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.DeviceID }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.DeviceID createDellStorageArrayInfoArrayDisksDCStorageObjectDeviceID() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.DeviceID();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Batteries.DCStorageObject.MasterMethodMask }
     * 
     */
    public DellStorage.ArrayInfo.Batteries.DCStorageObject.MasterMethodMask createDellStorageArrayInfoBatteriesDCStorageObjectMasterMethodMask() {
        return new DellStorage.ArrayInfo.Batteries.DCStorageObject.MasterMethodMask();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Enclosures.DCStorageObject.ObjStatus }
     * 
     */
    public DellStorage.ArrayInfo.Enclosures.DCStorageObject.ObjStatus createDellStorageArrayInfoEnclosuresDCStorageObjectObjStatus() {
        return new DellStorage.ArrayInfo.Enclosures.DCStorageObject.ObjStatus();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.Name }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.Name createDellStorageArrayInfoControllersDCStorageObjectName() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.Name();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.PatrolReadState }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.PatrolReadState createDellStorageArrayInfoControllersDCStorageObjectPatrolReadState() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.PatrolReadState();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.ObjID }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.ObjID createDellStorageArrayInfoControllersDCStorageObjectObjID() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.ObjID();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Batteries.DCStorageObject.TreeStatus }
     * 
     */
    public DellStorage.ArrayInfo.Batteries.DCStorageObject.TreeStatus createDellStorageArrayInfoBatteriesDCStorageObjectTreeStatus() {
        return new DellStorage.ArrayInfo.Batteries.DCStorageObject.TreeStatus();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.MinDrivesForRAID10 }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.MinDrivesForRAID10 createDellStorageArrayInfoControllersDCStorageObjectMinDrivesForRAID10() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.MinDrivesForRAID10();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.Nexus }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.Nexus createDellStorageArrayInfoArrayDisksDCStorageObjectNexus() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.Nexus();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Channels.DCStorageObject.Channel }
     * 
     */
    public DellStorage.ArrayInfo.Channels.DCStorageObject.Channel createDellStorageArrayInfoChannelsDCStorageObjectChannel() {
        return new DellStorage.ArrayInfo.Channels.DCStorageObject.Channel();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.CurrentMethodMask }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.CurrentMethodMask createDellStorageArrayInfoArrayDisksDCStorageObjectCurrentMethodMask() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.CurrentMethodMask();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.FirmwareVer }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.FirmwareVer createDellStorageArrayInfoControllersDCStorageObjectFirmwareVer() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.FirmwareVer();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.StripeSize }
     * 
     */
    public DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.StripeSize createDellStorageArrayInfoVirtualDisksDCStorageObjectStripeSize() {
        return new DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.StripeSize();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.Copyback }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.Copyback createDellStorageArrayInfoControllersDCStorageObjectCopyback() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.Copyback();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.VendorID }
     * 
     */
    public DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.VendorID createDellStorageArrayInfoVirtualDisksDCStorageObjectVendorID() {
        return new DellStorage.ArrayInfo.VirtualDisks.DCStorageObject.VendorID();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.DeviceSerialNumber }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.DeviceSerialNumber createDellStorageArrayInfoArrayDisksDCStorageObjectDeviceSerialNumber() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.DeviceSerialNumber();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.WritePolicyMask }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.WritePolicyMask createDellStorageArrayInfoControllersDCStorageObjectWritePolicyMask() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.WritePolicyMask();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.CtrlRaidLevel1E0RLQ0 }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.CtrlRaidLevel1E0RLQ0 createDellStorageArrayInfoControllersDCStorageObjectCtrlRaidLevel1E0RLQ0() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.CtrlRaidLevel1E0RLQ0();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Channels.DCStorageObject.Nexus }
     * 
     */
    public DellStorage.ArrayInfo.Channels.DCStorageObject.Nexus createDellStorageArrayInfoChannelsDCStorageObjectNexus() {
        return new DellStorage.ArrayInfo.Channels.DCStorageObject.Nexus();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ObjType }
     * 
     */
    public DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ObjType createDellStorageArrayInfoArrayDisksDCStorageObjectObjType() {
        return new DellStorage.ArrayInfo.ArrayDisks.DCStorageObject.ObjType();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxDrivesForRAID6 }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxDrivesForRAID6 createDellStorageArrayInfoControllersDCStorageObjectMaxDrivesForRAID6() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxDrivesForRAID6();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.ControllerNum }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.ControllerNum createDellStorageArrayInfoControllersDCStorageObjectControllerNum() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.ControllerNum();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.DefaultReadPolicy }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.DefaultReadPolicy createDellStorageArrayInfoControllersDCStorageObjectDefaultReadPolicy() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.DefaultReadPolicy();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.Nexus }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.Nexus createDellStorageArrayInfoControllersDCStorageObjectNexus() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.Nexus();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Batteries.DCStorageObject.BatteryLearnModeMask }
     * 
     */
    public DellStorage.ArrayInfo.Batteries.DCStorageObject.BatteryLearnModeMask createDellStorageArrayInfoBatteriesDCStorageObjectBatteryLearnModeMask() {
        return new DellStorage.ArrayInfo.Batteries.DCStorageObject.BatteryLearnModeMask();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.CacheSize }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.CacheSize createDellStorageArrayInfoControllersDCStorageObjectCacheSize() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.CacheSize();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Enclosures.DCStorageObject.EnclosureTarget }
     * 
     */
    public DellStorage.ArrayInfo.Enclosures.DCStorageObject.EnclosureTarget createDellStorageArrayInfoEnclosuresDCStorageObjectEnclosureTarget() {
        return new DellStorage.ArrayInfo.Enclosures.DCStorageObject.EnclosureTarget();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.MinDrivesForRAID0 }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.MinDrivesForRAID0 createDellStorageArrayInfoControllersDCStorageObjectMinDrivesForRAID0() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.MinDrivesForRAID0();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.DiskCachePolicyMask }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.DiskCachePolicyMask createDellStorageArrayInfoControllersDCStorageObjectDiskCachePolicyMask() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.DiskCachePolicyMask();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.CtrlMinCreateDiskSize }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.CtrlMinCreateDiskSize createDellStorageArrayInfoControllersDCStorageObjectCtrlMinCreateDiskSize() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.CtrlMinCreateDiskSize();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxVDsPerSpan }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxVDsPerSpan createDellStorageArrayInfoControllersDCStorageObjectMaxVDsPerSpan() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.MaxVDsPerSpan();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Enclosures.DCStorageObject.EnclosureID }
     * 
     */
    public DellStorage.ArrayInfo.Enclosures.DCStorageObject.EnclosureID createDellStorageArrayInfoEnclosuresDCStorageObjectEnclosureID() {
        return new DellStorage.ArrayInfo.Enclosures.DCStorageObject.EnclosureID();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.DefaultStripeSize }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.DefaultStripeSize createDellStorageArrayInfoControllersDCStorageObjectDefaultStripeSize() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.DefaultStripeSize();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.AlarmState }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.AlarmState createDellStorageArrayInfoControllersDCStorageObjectAlarmState() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.AlarmState();
    }


    /**
     * Create an instance of {@link DellStorage.ArrayInfo.Controllers.DCStorageObject.PCIBusNo }
     * 
     */
    public DellStorage.ArrayInfo.Controllers.DCStorageObject.PCIBusNo createDellStorageArrayInfoControllersDCStorageObjectPCIBusNo() {
        return new DellStorage.ArrayInfo.Controllers.DCStorageObject.PCIBusNo();
    }

}
