/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.18 at 11:10:55 AM CDT 
//

package com.dell.isg.smi.wsman.command.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Target" type="{http://schemas.dmtf.org/wbem/wscim/1/common}cimString"/>
 *         &lt;element name="RebootJobType" type="{http://schemas.dmtf.org/wbem/wscim/1/common}cimUnsignedShort"/>
 *         &lt;element name="ScheduledStartTime" type="{http://schemas.dmtf.org/wbem/wscim/1/common}cimString"/>
 *         &lt;element name="UntilTime" type="{http://schemas.dmtf.org/wbem/wscim/1/common}cimString"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "target", "rebootJobType", "scheduledStartTime", "untilTime" })
@XmlRootElement(name = "CreateTargetedConfigJob_INPUT")
public class CreateTargetedConfigJobINPUT {

    @XmlElement(name = "Target", required = true)
    protected CimString target;
    @XmlElement(name = "RebootJobType", required = true, nillable = true)
    protected CimUnsignedShort rebootJobType;
    @XmlElement(name = "ScheduledStartTime", required = true, nillable = true)
    protected CimString scheduledStartTime;
    @XmlElement(name = "UntilTime", required = true, nillable = true)
    protected CimString untilTime;


    /**
     * Gets the value of the target property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getTarget() {
        return target;
    }


    /**
     * Sets the value of the target property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setTarget(CimString value) {
        this.target = value;
    }


    /**
     * Gets the value of the rebootJobType property.
     * 
     * @return possible object is {@link CimUnsignedShort }
     * 
     */
    public CimUnsignedShort getRebootJobType() {
        return rebootJobType;
    }


    /**
     * Sets the value of the rebootJobType property.
     * 
     * @param value allowed object is {@link CimUnsignedShort }
     * 
     */
    public void setRebootJobType(CimUnsignedShort value) {
        this.rebootJobType = value;
    }


    /**
     * Gets the value of the scheduledStartTime property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getScheduledStartTime() {
        return scheduledStartTime;
    }


    /**
     * Sets the value of the scheduledStartTime property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setScheduledStartTime(CimString value) {
        this.scheduledStartTime = value;
    }


    /**
     * Gets the value of the untilTime property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getUntilTime() {
        return untilTime;
    }


    /**
     * Sets the value of the untilTime property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setUntilTime(CimString value) {
        this.untilTime = value;
    }

}
