/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.02 at 10:42:58 AM CDT 
//

package com.dell.isg.smi.wsman.command.entity;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import org.w3c.dom.Element;

/**
 * <p>
 * Java class for DCIM_SoftwareIdentity_Type complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DCIM_SoftwareIdentity_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}BuildNumber" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}Caption" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}ClassificationDescriptions" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}Classifications" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}CommunicationStatus" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}ComponentID" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}ComponentType" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}Description" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}DetailedStatus" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}DeviceID" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}ElementName" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}ExtendedResourceType" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}Generation" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}HealthState" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}IdentityInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}IdentityInfoValue" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}InstallDate" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}InstallationDate" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}InstanceID"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}IsEntity" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}IsLargeBuildNumber" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}Languages" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}LargeBuildNumber" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}MajorVersion" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}Manufacturer" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}MinExtendedResourceTypeBuildNumber" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}MinExtendedResourceTypeMajorVersion" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}MinExtendedResourceTypeMinorVersion" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}MinExtendedResourceTypeRevisionNumber" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}MinorVersion" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}Name" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}OperatingStatus" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}OperationalStatus" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}OtherExtendedResourceTypeDescription" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}PrimaryStatus" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}ReleaseDate" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}RevisionNumber" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}RevisionString" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}SerialNumber" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}Status" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}StatusDescriptions" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}SubDeviceID" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}SubVendorID" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}TargetOSTypes" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}TargetOperatingSystems" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}TargetTypes" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}Updateable" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}VendorID" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}VersionString" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity}impactsTPMmeasurements" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DCIM_SoftwareIdentity_Type", namespace = "http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_SoftwareIdentity", propOrder = { "buildNumber", "caption", "classificationDescriptions", "classifications", "communicationStatus", "componentID", "componentType", "description", "detailedStatus", "deviceID", "elementName", "extendedResourceType", "generation", "healthState", "identityInfoType", "identityInfoValue", "installDate", "installationDate", "instanceID", "isEntity", "isLargeBuildNumber", "languages", "largeBuildNumber", "majorVersion", "manufacturer", "minExtendedResourceTypeBuildNumber", "minExtendedResourceTypeMajorVersion", "minExtendedResourceTypeMinorVersion", "minExtendedResourceTypeRevisionNumber", "minorVersion", "name", "operatingStatus", "operationalStatus", "otherExtendedResourceTypeDescription", "primaryStatus", "releaseDate", "revisionNumber", "revisionString", "serialNumber", "status", "statusDescriptions", "subDeviceID", "subVendorID", "updateable", "targetOSTypes", "targetOperatingSystems", "targetTypes", "vendorID", "versionString", "impactsTPMmeasurements", "any" })
public class DCIMSoftwareIdentityType {

    @XmlElement(name = "BuildNumber", nillable = true)
    protected CimUnsignedShort buildNumber;
    @XmlElement(name = "Caption", nillable = true)
    protected Caption caption;
    @XmlElement(name = "ClassificationDescriptions", nillable = true)
    protected List<CimString> classificationDescriptions;
    @XmlElement(name = "Classifications", nillable = true)
    protected List<Classifications> classifications;
    @XmlElement(name = "CommunicationStatus", nillable = true)
    protected CommunicationStatus communicationStatus;
    @XmlElement(name = "ComponentID", nillable = true)
    protected CimString componentID;
    @XmlElement(name = "ComponentType", nillable = true)
    protected CimString componentType;
    @XmlElement(name = "Description", nillable = true)
    protected CimString description;
    @XmlElement(name = "DetailedStatus", nillable = true)
    protected DetailedStatus detailedStatus;
    @XmlElement(name = "DeviceID", nillable = true)
    protected CimString deviceID;
    @XmlElement(name = "ElementName", nillable = true)
    protected CimString elementName;
    @XmlElement(name = "ExtendedResourceType", nillable = true)
    protected ExtendedResourceType extendedResourceType;
    @XmlElement(name = "Generation", nillable = true)
    protected CimUnsignedLong generation;
    @XmlElement(name = "HealthState", nillable = true)
    protected HealthState healthState;
    @XmlElement(name = "IdentityInfoType", nillable = true)
    protected List<IdentityInfoType> identityInfoType;
    @XmlElement(name = "IdentityInfoValue", nillable = true)
    protected List<IdentityInfoValue> identityInfoValue;
    @XmlElement(name = "InstallDate", nillable = true)
    protected CimDateTime installDate;
    @XmlElement(name = "InstallationDate", nillable = true)
    protected CimString installationDate;
    @XmlElement(name = "InstanceID", required = true)
    protected CimString instanceID;
    @XmlElement(name = "IsEntity", nillable = true)
    protected CimBoolean isEntity;
    @XmlElement(name = "IsLargeBuildNumber", nillable = true)
    protected CimBoolean isLargeBuildNumber;
    @XmlElement(name = "Languages", nillable = true)
    protected List<CimString> languages;
    @XmlElement(name = "LargeBuildNumber", nillable = true)
    protected CimUnsignedLong largeBuildNumber;
    @XmlElement(name = "MajorVersion", nillable = true)
    protected CimUnsignedShort majorVersion;
    @XmlElement(name = "Manufacturer", nillable = true)
    protected CimString manufacturer;
    @XmlElement(name = "MinExtendedResourceTypeBuildNumber", nillable = true)
    protected CimUnsignedShort minExtendedResourceTypeBuildNumber;
    @XmlElement(name = "MinExtendedResourceTypeMajorVersion", nillable = true)
    protected CimUnsignedShort minExtendedResourceTypeMajorVersion;
    @XmlElement(name = "MinExtendedResourceTypeMinorVersion", nillable = true)
    protected CimUnsignedShort minExtendedResourceTypeMinorVersion;
    @XmlElement(name = "MinExtendedResourceTypeRevisionNumber", nillable = true)
    protected CimUnsignedShort minExtendedResourceTypeRevisionNumber;
    @XmlElement(name = "MinorVersion", nillable = true)
    protected CimUnsignedShort minorVersion;
    @XmlElement(name = "Name", nillable = true)
    protected Name name;
    @XmlElement(name = "OperatingStatus", nillable = true)
    protected OperatingStatus operatingStatus;
    @XmlElement(name = "OperationalStatus", nillable = true)
    protected List<OperationalStatus> operationalStatus;
    @XmlElement(name = "OtherExtendedResourceTypeDescription", nillable = true)
    protected CimString otherExtendedResourceTypeDescription;
    @XmlElement(name = "PrimaryStatus", nillable = true)
    protected PrimaryStatus primaryStatus;
    @XmlElement(name = "ReleaseDate", nillable = true)
    protected CimDateTime releaseDate;
    @XmlElement(name = "RevisionNumber", nillable = true)
    protected CimUnsignedShort revisionNumber;
    @XmlElement(name = "RevisionString", nillable = true)
    protected CimString revisionString;
    @XmlElement(name = "SerialNumber", nillable = true)
    protected CimString serialNumber;
    @XmlElement(name = "Status", nillable = true)
    protected CimString status;
    @XmlElement(name = "StatusDescriptions", nillable = true)
    protected List<CimString> statusDescriptions;
    @XmlElement(name = "SubDeviceID", nillable = true)
    protected CimString subDeviceID;
    @XmlElement(name = "SubVendorID", nillable = true)
    protected CimString subVendorID;
    @XmlElement(name = "TargetOSTypes", nillable = true)
    protected List<TargetOSTypes> targetOSTypes;
    @XmlElement(name = "TargetOperatingSystems", nillable = true)
    protected List<CimString> targetOperatingSystems;
    @XmlElement(name = "TargetTypes", nillable = true)
    protected List<CimString> targetTypes;
    @XmlElement(name = "Updateable", nillable = true)
    protected CimBoolean updateable;
    @XmlElement(name = "VendorID", nillable = true)
    protected CimString vendorID;
    @XmlElement(name = "VersionString", nillable = true)
    protected CimString versionString;
    @XmlElement(nillable = true)
    protected CimBoolean impactsTPMmeasurements;
    @XmlAnyElement(lax = true)
    protected List<Object> any;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();


    /**
     * Gets the value of the buildNumber property.
     * 
     * @return possible object is {@link CimUnsignedShort }
     * 
     */
    public CimUnsignedShort getBuildNumber() {
        return buildNumber;
    }


    /**
     * Sets the value of the buildNumber property.
     * 
     * @param value allowed object is {@link CimUnsignedShort }
     * 
     */
    public void setBuildNumber(CimUnsignedShort value) {
        this.buildNumber = value;
    }


    /**
     * Gets the value of the caption property.
     * 
     * @return possible object is {@link Caption }
     * 
     */
    public Caption getCaption() {
        return caption;
    }


    /**
     * Sets the value of the caption property.
     * 
     * @param value allowed object is {@link Caption }
     * 
     */
    public void setCaption(Caption value) {
        this.caption = value;
    }


    /**
     * Gets the value of the classificationDescriptions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the classificationDescriptions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getClassificationDescriptions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link CimString }
     * 
     * 
     */
    public List<CimString> getClassificationDescriptions() {
        if (classificationDescriptions == null) {
            classificationDescriptions = new ArrayList<CimString>();
        }
        return this.classificationDescriptions;
    }


    /**
     * Gets the value of the classifications property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the classifications property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getClassifications().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Classifications }
     * 
     * 
     */
    public List<Classifications> getClassifications() {
        if (classifications == null) {
            classifications = new ArrayList<Classifications>();
        }
        return this.classifications;
    }


    /**
     * Gets the value of the communicationStatus property.
     * 
     * @return possible object is {@link CommunicationStatus }
     * 
     */
    public CommunicationStatus getCommunicationStatus() {
        return communicationStatus;
    }


    /**
     * Sets the value of the communicationStatus property.
     * 
     * @param value allowed object is {@link CommunicationStatus }
     * 
     */
    public void setCommunicationStatus(CommunicationStatus value) {
        this.communicationStatus = value;
    }


    /**
     * Gets the value of the componentID property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getComponentID() {
        return componentID;
    }


    /**
     * Sets the value of the componentID property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setComponentID(CimString value) {
        this.componentID = value;
    }


    /**
     * Gets the value of the componentType property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getComponentType() {
        return componentType;
    }


    /**
     * Sets the value of the componentType property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setComponentType(CimString value) {
        this.componentType = value;
    }


    /**
     * Gets the value of the description property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getDescription() {
        return description;
    }


    /**
     * Sets the value of the description property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setDescription(CimString value) {
        this.description = value;
    }


    /**
     * Gets the value of the detailedStatus property.
     * 
     * @return possible object is {@link DetailedStatus }
     * 
     */
    public DetailedStatus getDetailedStatus() {
        return detailedStatus;
    }


    /**
     * Sets the value of the detailedStatus property.
     * 
     * @param value allowed object is {@link DetailedStatus }
     * 
     */
    public void setDetailedStatus(DetailedStatus value) {
        this.detailedStatus = value;
    }


    /**
     * Gets the value of the deviceID property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getDeviceID() {
        return deviceID;
    }


    /**
     * Sets the value of the deviceID property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setDeviceID(CimString value) {
        this.deviceID = value;
    }


    /**
     * Gets the value of the elementName property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getElementName() {
        return elementName;
    }


    /**
     * Sets the value of the elementName property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setElementName(CimString value) {
        this.elementName = value;
    }


    /**
     * Gets the value of the extendedResourceType property.
     * 
     * @return possible object is {@link ExtendedResourceType }
     * 
     */
    public ExtendedResourceType getExtendedResourceType() {
        return extendedResourceType;
    }


    /**
     * Sets the value of the extendedResourceType property.
     * 
     * @param value allowed object is {@link ExtendedResourceType }
     * 
     */
    public void setExtendedResourceType(ExtendedResourceType value) {
        this.extendedResourceType = value;
    }


    /**
     * Gets the value of the generation property.
     * 
     * @return possible object is {@link CimUnsignedLong }
     * 
     */
    public CimUnsignedLong getGeneration() {
        return generation;
    }


    /**
     * Sets the value of the generation property.
     * 
     * @param value allowed object is {@link CimUnsignedLong }
     * 
     */
    public void setGeneration(CimUnsignedLong value) {
        this.generation = value;
    }


    /**
     * Gets the value of the healthState property.
     * 
     * @return possible object is {@link HealthState }
     * 
     */
    public HealthState getHealthState() {
        return healthState;
    }


    /**
     * Sets the value of the healthState property.
     * 
     * @param value allowed object is {@link HealthState }
     * 
     */
    public void setHealthState(HealthState value) {
        this.healthState = value;
    }


    /**
     * Gets the value of the identityInfoType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identityInfoType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getIdentityInfoType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link IdentityInfoType }
     * 
     * 
     */
    public List<IdentityInfoType> getIdentityInfoType() {
        if (identityInfoType == null) {
            identityInfoType = new ArrayList<IdentityInfoType>();
        }
        return this.identityInfoType;
    }


    /**
     * Gets the value of the identityInfoValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identityInfoValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getIdentityInfoValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link IdentityInfoValue }
     * 
     * 
     */
    public List<IdentityInfoValue> getIdentityInfoValue() {
        if (identityInfoValue == null) {
            identityInfoValue = new ArrayList<IdentityInfoValue>();
        }
        return this.identityInfoValue;
    }


    /**
     * Gets the value of the installDate property.
     * 
     * @return possible object is {@link CimDateTime }
     * 
     */
    public CimDateTime getInstallDate() {
        return installDate;
    }


    /**
     * Sets the value of the installDate property.
     * 
     * @param value allowed object is {@link CimDateTime }
     * 
     */
    public void setInstallDate(CimDateTime value) {
        this.installDate = value;
    }


    /**
     * Gets the value of the installationDate property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getInstallationDate() {
        return installationDate;
    }


    /**
     * Sets the value of the installationDate property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setInstallationDate(CimString value) {
        this.installationDate = value;
    }


    /**
     * Gets the value of the instanceID property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getInstanceID() {
        return instanceID;
    }


    /**
     * Sets the value of the instanceID property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setInstanceID(CimString value) {
        this.instanceID = value;
    }


    /**
     * Gets the value of the isEntity property.
     * 
     * @return possible object is {@link CimBoolean }
     * 
     */
    public CimBoolean getIsEntity() {
        return isEntity;
    }


    /**
     * Sets the value of the isEntity property.
     * 
     * @param value allowed object is {@link CimBoolean }
     * 
     */
    public void setIsEntity(CimBoolean value) {
        this.isEntity = value;
    }


    /**
     * Gets the value of the isLargeBuildNumber property.
     * 
     * @return possible object is {@link CimBoolean }
     * 
     */
    public CimBoolean getIsLargeBuildNumber() {
        return isLargeBuildNumber;
    }


    /**
     * Sets the value of the isLargeBuildNumber property.
     * 
     * @param value allowed object is {@link CimBoolean }
     * 
     */
    public void setIsLargeBuildNumber(CimBoolean value) {
        this.isLargeBuildNumber = value;
    }


    /**
     * Gets the value of the languages property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the languages property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getLanguages().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link CimString }
     * 
     * 
     */
    public List<CimString> getLanguages() {
        if (languages == null) {
            languages = new ArrayList<CimString>();
        }
        return this.languages;
    }


    /**
     * Gets the value of the largeBuildNumber property.
     * 
     * @return possible object is {@link CimUnsignedLong }
     * 
     */
    public CimUnsignedLong getLargeBuildNumber() {
        return largeBuildNumber;
    }


    /**
     * Sets the value of the largeBuildNumber property.
     * 
     * @param value allowed object is {@link CimUnsignedLong }
     * 
     */
    public void setLargeBuildNumber(CimUnsignedLong value) {
        this.largeBuildNumber = value;
    }


    /**
     * Gets the value of the majorVersion property.
     * 
     * @return possible object is {@link CimUnsignedShort }
     * 
     */
    public CimUnsignedShort getMajorVersion() {
        return majorVersion;
    }


    /**
     * Sets the value of the majorVersion property.
     * 
     * @param value allowed object is {@link CimUnsignedShort }
     * 
     */
    public void setMajorVersion(CimUnsignedShort value) {
        this.majorVersion = value;
    }


    /**
     * Gets the value of the manufacturer property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getManufacturer() {
        return manufacturer;
    }


    /**
     * Sets the value of the manufacturer property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setManufacturer(CimString value) {
        this.manufacturer = value;
    }


    /**
     * Gets the value of the minExtendedResourceTypeBuildNumber property.
     * 
     * @return possible object is {@link CimUnsignedShort }
     * 
     */
    public CimUnsignedShort getMinExtendedResourceTypeBuildNumber() {
        return minExtendedResourceTypeBuildNumber;
    }


    /**
     * Sets the value of the minExtendedResourceTypeBuildNumber property.
     * 
     * @param value allowed object is {@link CimUnsignedShort }
     * 
     */
    public void setMinExtendedResourceTypeBuildNumber(CimUnsignedShort value) {
        this.minExtendedResourceTypeBuildNumber = value;
    }


    /**
     * Gets the value of the minExtendedResourceTypeMajorVersion property.
     * 
     * @return possible object is {@link CimUnsignedShort }
     * 
     */
    public CimUnsignedShort getMinExtendedResourceTypeMajorVersion() {
        return minExtendedResourceTypeMajorVersion;
    }


    /**
     * Sets the value of the minExtendedResourceTypeMajorVersion property.
     * 
     * @param value allowed object is {@link CimUnsignedShort }
     * 
     */
    public void setMinExtendedResourceTypeMajorVersion(CimUnsignedShort value) {
        this.minExtendedResourceTypeMajorVersion = value;
    }


    /**
     * Gets the value of the minExtendedResourceTypeMinorVersion property.
     * 
     * @return possible object is {@link CimUnsignedShort }
     * 
     */
    public CimUnsignedShort getMinExtendedResourceTypeMinorVersion() {
        return minExtendedResourceTypeMinorVersion;
    }


    /**
     * Sets the value of the minExtendedResourceTypeMinorVersion property.
     * 
     * @param value allowed object is {@link CimUnsignedShort }
     * 
     */
    public void setMinExtendedResourceTypeMinorVersion(CimUnsignedShort value) {
        this.minExtendedResourceTypeMinorVersion = value;
    }


    /**
     * Gets the value of the minExtendedResourceTypeRevisionNumber property.
     * 
     * @return possible object is {@link CimUnsignedShort }
     * 
     */
    public CimUnsignedShort getMinExtendedResourceTypeRevisionNumber() {
        return minExtendedResourceTypeRevisionNumber;
    }


    /**
     * Sets the value of the minExtendedResourceTypeRevisionNumber property.
     * 
     * @param value allowed object is {@link CimUnsignedShort }
     * 
     */
    public void setMinExtendedResourceTypeRevisionNumber(CimUnsignedShort value) {
        this.minExtendedResourceTypeRevisionNumber = value;
    }


    /**
     * Gets the value of the minorVersion property.
     * 
     * @return possible object is {@link CimUnsignedShort }
     * 
     */
    public CimUnsignedShort getMinorVersion() {
        return minorVersion;
    }


    /**
     * Sets the value of the minorVersion property.
     * 
     * @param value allowed object is {@link CimUnsignedShort }
     * 
     */
    public void setMinorVersion(CimUnsignedShort value) {
        this.minorVersion = value;
    }


    /**
     * Gets the value of the name property.
     * 
     * @return possible object is {@link Name }
     * 
     */
    public Name getName() {
        return name;
    }


    /**
     * Sets the value of the name property.
     * 
     * @param value allowed object is {@link Name }
     * 
     */
    public void setName(Name value) {
        this.name = value;
    }


    /**
     * Gets the value of the operatingStatus property.
     * 
     * @return possible object is {@link OperatingStatus }
     * 
     */
    public OperatingStatus getOperatingStatus() {
        return operatingStatus;
    }


    /**
     * Sets the value of the operatingStatus property.
     * 
     * @param value allowed object is {@link OperatingStatus }
     * 
     */
    public void setOperatingStatus(OperatingStatus value) {
        this.operatingStatus = value;
    }


    /**
     * Gets the value of the operationalStatus property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the operationalStatus property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getOperationalStatus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link OperationalStatus }
     * 
     * 
     */
    public List<OperationalStatus> getOperationalStatus() {
        if (operationalStatus == null) {
            operationalStatus = new ArrayList<OperationalStatus>();
        }
        return this.operationalStatus;
    }


    /**
     * Gets the value of the otherExtendedResourceTypeDescription property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getOtherExtendedResourceTypeDescription() {
        return otherExtendedResourceTypeDescription;
    }


    /**
     * Sets the value of the otherExtendedResourceTypeDescription property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setOtherExtendedResourceTypeDescription(CimString value) {
        this.otherExtendedResourceTypeDescription = value;
    }


    /**
     * Gets the value of the primaryStatus property.
     * 
     * @return possible object is {@link PrimaryStatus }
     * 
     */
    public PrimaryStatus getPrimaryStatus() {
        return primaryStatus;
    }


    /**
     * Sets the value of the primaryStatus property.
     * 
     * @param value allowed object is {@link PrimaryStatus }
     * 
     */
    public void setPrimaryStatus(PrimaryStatus value) {
        this.primaryStatus = value;
    }


    /**
     * Gets the value of the releaseDate property.
     * 
     * @return possible object is {@link CimDateTime }
     * 
     */
    public CimDateTime getReleaseDate() {
        return releaseDate;
    }


    /**
     * Sets the value of the releaseDate property.
     * 
     * @param value allowed object is {@link CimDateTime }
     * 
     */
    public void setReleaseDate(CimDateTime value) {
        this.releaseDate = value;
    }


    /**
     * Gets the value of the revisionNumber property.
     * 
     * @return possible object is {@link CimUnsignedShort }
     * 
     */
    public CimUnsignedShort getRevisionNumber() {
        return revisionNumber;
    }


    /**
     * Sets the value of the revisionNumber property.
     * 
     * @param value allowed object is {@link CimUnsignedShort }
     * 
     */
    public void setRevisionNumber(CimUnsignedShort value) {
        this.revisionNumber = value;
    }


    /**
     * Gets the value of the revisionString property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getRevisionString() {
        return revisionString;
    }


    /**
     * Sets the value of the revisionString property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setRevisionString(CimString value) {
        this.revisionString = value;
    }


    /**
     * Gets the value of the serialNumber property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getSerialNumber() {
        return serialNumber;
    }


    /**
     * Sets the value of the serialNumber property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setSerialNumber(CimString value) {
        this.serialNumber = value;
    }


    /**
     * Gets the value of the status property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getStatus() {
        return status;
    }


    /**
     * Sets the value of the status property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setStatus(CimString value) {
        this.status = value;
    }


    /**
     * Gets the value of the statusDescriptions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the statusDescriptions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getStatusDescriptions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link CimString }
     * 
     * 
     */
    public List<CimString> getStatusDescriptions() {
        if (statusDescriptions == null) {
            statusDescriptions = new ArrayList<CimString>();
        }
        return this.statusDescriptions;
    }


    /**
     * Gets the value of the subDeviceID property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getSubDeviceID() {
        return subDeviceID;
    }


    /**
     * Sets the value of the subDeviceID property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setSubDeviceID(CimString value) {
        this.subDeviceID = value;
    }


    /**
     * Gets the value of the subVendorID property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getSubVendorID() {
        return subVendorID;
    }


    /**
     * Sets the value of the subVendorID property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setSubVendorID(CimString value) {
        this.subVendorID = value;
    }


    /**
     * Gets the value of the targetOSTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the targetOSTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getTargetOSTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link TargetOSTypes }
     * 
     * 
     */
    public List<TargetOSTypes> getTargetOSTypes() {
        if (targetOSTypes == null) {
            targetOSTypes = new ArrayList<TargetOSTypes>();
        }
        return this.targetOSTypes;
    }


    /**
     * Gets the value of the targetOperatingSystems property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the targetOperatingSystems property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getTargetOperatingSystems().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link CimString }
     * 
     * 
     */
    public List<CimString> getTargetOperatingSystems() {
        if (targetOperatingSystems == null) {
            targetOperatingSystems = new ArrayList<CimString>();
        }
        return this.targetOperatingSystems;
    }


    /**
     * Gets the value of the targetTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the targetTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getTargetTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link CimString }
     * 
     * 
     */
    public List<CimString> getTargetTypes() {
        if (targetTypes == null) {
            targetTypes = new ArrayList<CimString>();
        }
        return this.targetTypes;
    }


    /**
     * Gets the value of the updateable property.
     * 
     * @return possible object is {@link CimBoolean }
     * 
     */
    public CimBoolean isUpdateable() {
        return updateable;
    }


    /**
     * Sets the value of the updateable property.
     * 
     * @param value allowed object is {@link CimBoolean }
     * 
     */
    public void setUpdateable(CimBoolean value) {
        this.updateable = value;
    }


    /**
     * Gets the value of the vendorID property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getVendorID() {
        return vendorID;
    }


    /**
     * Sets the value of the vendorID property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setVendorID(CimString value) {
        this.vendorID = value;
    }


    /**
     * Gets the value of the versionString property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getVersionString() {
        return versionString;
    }


    /**
     * Sets the value of the versionString property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setVersionString(CimString value) {
        this.versionString = value;
    }


    /**
     * Gets the value of the impactsTPMmeasurements property.
     * 
     * @return possible object is {@link CimBoolean }
     * 
     */
    public CimBoolean getImpactsTPMmeasurements() {
        return impactsTPMmeasurements;
    }


    /**
     * Sets the value of the impactsTPMmeasurements property.
     * 
     * @param value allowed object is {@link CimBoolean }
     * 
     */
    public void setImpactsTPMmeasurements(CimBoolean value) {
        this.impactsTPMmeasurements = value;
    }


    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Element } {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }


    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
