/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.23 at 08:16:53 PM CDT 
//

package com.dell.isg.smi.wsman.command.entity;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import org.w3c.dom.Element;

/**
 * <p>
 * Java class for DCIM_NICView_Type complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DCIM_NICView_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}BusNumber" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}Caption" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}CurrentMACAddress" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}DataBusWidth" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}Description" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}DeviceNumber" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}ElementName" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}FQDD" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}FunctionNumber" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}Generation" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}InstanceID" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}LastSystemInventoryTime" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}LastUpdateTime" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}PCIDeviceID" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}PCISubDeviceID" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}PCISubVendorID" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}PCIVendorID" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}PermanentMACAddress" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}PermanentiSCSIMACAddress" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}ProductName" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}SlotLength" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}SlotType" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DCIM_NICView_Type", namespace = "http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView", propOrder = { "mediaType", "minBandwidth", "receiveFlowControl", "wwn", "wwpn", "autoNegotiation", "controllerBIOSVersion", "familyVersion", "linkDuplex", "linkSpeed", "maxBandwidth", "nicMode", "transmitFlowControl", "vendorName", "virtWwn", "virtWwpn", "fCoEOffloadMode", "fCoEWwnn", "iScsiOffloadMode", "busNumber", "caption", "currentMACAddress", "dataBusWidth", "description", "deviceNumber", "elementName", "fqdd", "functionNumber", "generation", "instanceID", "lastSystemInventoryTime", "lastUpdateTime", "pciDeviceID", "pciSubDeviceID", "pciSubVendorID", "pciVendorID", "permanentMACAddress", "permanentiSCSIMACAddress", "productName", "slotLength", "slotType", "any", "linkStatus", "osDriverState", "macAddress", "iscsiMacAddress", "virtualMacAddress", "virtualIscsiMacAddress", "teaming", "iscsiOffloadSupport", "toeSupport", "legacyBootProtocol", "icsciBootMode", "iscsiInitiatorIpAddress", "iscsiInitiatorSubnet", "iscsiInitiatorGateway", "iscsiInitiatorPrimaryDns", "iscsiInitiatorSecondryDns", "iscsiInitiatorName" })
public class DCIMNICViewType {

    @XmlElement(name = "BusNumber", nillable = true)
    protected CimUnsignedByte busNumber;
    @XmlElement(name = "Caption", nillable = true)
    protected Caption caption;
    @XmlElement(name = "CurrentMACAddress", nillable = true)
    protected CurrentMACAddress currentMACAddress;
    @XmlElement(name = "DataBusWidth", nillable = true)
    protected CimString dataBusWidth;
    @XmlElement(name = "DeviceDescription", nillable = true)
    protected CimString description;
    @XmlElement(name = "DeviceNumber", nillable = true)
    protected CimUnsignedByte deviceNumber;
    @XmlElement(name = "ElementName", nillable = true)
    protected CimString elementName;
    @XmlElement(name = "FQDD", nillable = true)
    protected CimString fqdd;
    @XmlElement(name = "FunctionNumber", nillable = true)
    protected CimUnsignedByte functionNumber;
    @XmlElement(name = "Generation", nillable = true)
    protected CimUnsignedLong generation;
    @XmlElement(name = "InstanceID", nillable = true)
    protected CimString instanceID;
    @XmlElement(name = "LastSystemInventoryTime", nillable = true)
    protected CimString lastSystemInventoryTime;
    @XmlElement(name = "LastUpdateTime", nillable = true)
    protected CimString lastUpdateTime;
    @XmlElement(name = "PCIDeviceID", nillable = true)
    protected CimString pciDeviceID;
    @XmlElement(name = "PCISubDeviceID", nillable = true)
    protected CimString pciSubDeviceID;
    @XmlElement(name = "PCISubVendorID", nillable = true)
    protected CimString pciSubVendorID;
    @XmlElement(name = "PCIVendorID", nillable = true)
    protected CimString pciVendorID;
    @XmlElement(name = "PermanentMACAddress", nillable = true)
    protected PermanentMACAddress permanentMACAddress;
    @XmlElement(name = "PermanentiSCSIMACAddress", nillable = true)
    protected PermanentiSCSIMACAddress permanentiSCSIMACAddress;
    @XmlElement(name = "ProductName", nillable = true)
    protected ProductName productName;
    @XmlElement(name = "SlotLength", nillable = true)
    protected CimString slotLength;
    @XmlElement(name = "SlotType", nillable = true)
    protected CimString slotType;
    @XmlElement(name = "AutoNegotiation", nillable = true)
    protected CimString autoNegotiation;
    @XmlElement(name = "ControllerBIOSVersion", nillable = true)
    protected CimString controllerBIOSVersion;
    @XmlElement(name = "FamilyVersion", nillable = true)
    protected CimString familyVersion;
    @XmlElement(name = "LinkDuplex", nillable = true)
    protected CimString linkDuplex;
    @XmlElement(name = "LinkSpeed", nillable = true)
    protected CimString linkSpeed;
    @XmlElement(name = "MaxBandwidth", nillable = true)
    protected CimString maxBandwidth;
    @XmlElement(name = "NicMode", nillable = true)
    protected CimString nicMode;
    @XmlElement(name = "TransmitFlowControl", nillable = true)
    protected CimString transmitFlowControl;
    @XmlElement(name = "VendorName", nillable = true)
    protected CimString vendorName;
    @XmlElement(name = "VirtWWN", nillable = true)
    protected CimString virtWwn;
    @XmlElement(name = "VirtWWPN", nillable = true)
    protected CimString virtWwpn;
    @XmlElement(name = "FCoEOffloadMode", nillable = true)
    protected CimString fCoEOffloadMode;
    @XmlElement(name = "FCoEWWNN", nillable = true)
    protected CimString fCoEWwnn;
    @XmlElement(name = "iScsiOffloadMode", nillable = true)
    protected CimString iScsiOffloadMode;
    @XmlElement(name = "MediaType", nillable = true)
    protected CimString mediaType;
    @XmlElement(name = "MinBandwidth", nillable = true)
    protected CimString minBandwidth;
    @XmlElement(name = "ReceiveFlowControl", nillable = true)
    protected CimString receiveFlowControl;
    @XmlElement(name = "WWN", nillable = true)
    protected CimString wwn;
    @XmlElement(name = "WWPN", nillable = true)
    protected CimString wwpn;
    @XmlAnyElement(lax = true)
    protected List<Object> any;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    private String linkStatus;
    private String osDriverState;
    private String macAddress;
    private String iscsiMacAddress;
    private String virtualMacAddress;
    private String virtualIscsiMacAddress;
    private String teaming;
    private String iscsiOffloadSupport;
    private String toeSupport;
    private String legacyBootProtocol;
    private String icsciBootMode;
    private String iscsiInitiatorIpAddress;
    private String iscsiInitiatorSubnet;
    private String iscsiInitiatorGateway;
    private String iscsiInitiatorPrimaryDns;
    private String iscsiInitiatorSecondryDns;
    private String iscsiInitiatorName;


    /**
     * Gets the value of the busNumber property.
     * 
     * @return possible object is {@link CimUnsignedByte }
     * 
     */
    public CimUnsignedByte getBusNumber() {
        return busNumber;
    }


    /**
     * Sets the value of the busNumber property.
     * 
     * @param value allowed object is {@link CimUnsignedByte }
     * 
     */
    public void setBusNumber(CimUnsignedByte value) {
        this.busNumber = value;
    }


    /**
     * Gets the value of the caption property.
     * 
     * @return possible object is {@link Caption }
     * 
     */
    public Caption getCaption() {
        return caption;
    }


    /**
     * Sets the value of the caption property.
     * 
     * @param value allowed object is {@link Caption }
     * 
     */
    public void setCaption(Caption value) {
        this.caption = value;
    }


    /**
     * Gets the value of the currentMACAddress property.
     * 
     * @return possible object is {@link CurrentMACAddress }
     * 
     */
    public CurrentMACAddress getCurrentMACAddress() {
        return currentMACAddress;
    }


    /**
     * Sets the value of the currentMACAddress property.
     * 
     * @param value allowed object is {@link CurrentMACAddress }
     * 
     */
    public void setCurrentMACAddress(CurrentMACAddress value) {
        this.currentMACAddress = value;
    }


    /**
     * Gets the value of the dataBusWidth property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getDataBusWidth() {
        return dataBusWidth;
    }


    /**
     * Sets the value of the dataBusWidth property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setDataBusWidth(CimString value) {
        this.dataBusWidth = value;
    }


    /**
     * Gets the value of the description property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getDescription() {
        return description;
    }


    /**
     * Sets the value of the description property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setDescription(CimString value) {
        this.description = value;
    }


    /**
     * Gets the value of the deviceNumber property.
     * 
     * @return possible object is {@link CimUnsignedByte }
     * 
     */
    public CimUnsignedByte getDeviceNumber() {
        return deviceNumber;
    }


    /**
     * Sets the value of the deviceNumber property.
     * 
     * @param value allowed object is {@link CimUnsignedByte }
     * 
     */
    public void setDeviceNumber(CimUnsignedByte value) {
        this.deviceNumber = value;
    }


    /**
     * Gets the value of the elementName property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getElementName() {
        return elementName;
    }


    /**
     * Sets the value of the elementName property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setElementName(CimString value) {
        this.elementName = value;
    }


    /**
     * Gets the value of the functionNumber property.
     * 
     * @return possible object is {@link CimUnsignedByte }
     * 
     */
    public CimUnsignedByte getFunctionNumber() {
        return functionNumber;
    }


    /**
     * Sets the value of the functionNumber property.
     * 
     * @param value allowed object is {@link CimUnsignedByte }
     * 
     */
    public void setFunctionNumber(CimUnsignedByte value) {
        this.functionNumber = value;
    }


    /**
     * Gets the value of the generation property.
     * 
     * @return possible object is {@link CimUnsignedLong }
     * 
     */
    public CimUnsignedLong getGeneration() {
        return generation;
    }


    /**
     * Sets the value of the generation property.
     * 
     * @param value allowed object is {@link CimUnsignedLong }
     * 
     */
    public void setGeneration(CimUnsignedLong value) {
        this.generation = value;
    }


    /**
     * Gets the value of the instanceID property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getInstanceID() {
        return instanceID;
    }


    /**
     * Sets the value of the instanceID property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setInstanceID(CimString value) {
        this.instanceID = value;
    }


    /**
     * Gets the value of the lastSystemInventoryTime property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getLastSystemInventoryTime() {
        return lastSystemInventoryTime;
    }


    /**
     * Sets the value of the lastSystemInventoryTime property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setLastSystemInventoryTime(CimString value) {
        this.lastSystemInventoryTime = value;
    }


    /**
     * Gets the value of the lastUpdateTime property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getLastUpdateTime() {
        return lastUpdateTime;
    }


    /**
     * Sets the value of the lastUpdateTime property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setLastUpdateTime(CimString value) {
        this.lastUpdateTime = value;
    }


    /**
     * Gets the value of the permanentMACAddress property.
     * 
     * @return possible object is {@link PermanentMACAddress }
     * 
     */
    public PermanentMACAddress getPermanentMACAddress() {
        return permanentMACAddress;
    }


    /**
     * Sets the value of the permanentMACAddress property.
     * 
     * @param value allowed object is {@link PermanentMACAddress }
     * 
     */
    public void setPermanentMACAddress(PermanentMACAddress value) {
        this.permanentMACAddress = value;
    }


    /**
     * Gets the value of the permanentiSCSIMACAddress property.
     * 
     * @return possible object is {@link PermanentiSCSIMACAddress }
     * 
     */
    public PermanentiSCSIMACAddress getPermanentiSCSIMACAddress() {
        return permanentiSCSIMACAddress;
    }


    /**
     * Sets the value of the permanentiSCSIMACAddress property.
     * 
     * @param value allowed object is {@link PermanentiSCSIMACAddress }
     * 
     */
    public void setPermanentiSCSIMACAddress(PermanentiSCSIMACAddress value) {
        this.permanentiSCSIMACAddress = value;
    }


    /**
     * Gets the value of the productName property.
     * 
     * @return possible object is {@link ProductName }
     * 
     */
    public ProductName getProductName() {
        return productName;
    }


    /**
     * Sets the value of the productName property.
     * 
     * @param value allowed object is {@link ProductName }
     * 
     */
    public void setProductName(ProductName value) {
        this.productName = value;
    }


    /**
     * Gets the value of the slotLength property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getSlotLength() {
        return slotLength;
    }


    /**
     * Sets the value of the slotLength property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setSlotLength(CimString value) {
        this.slotLength = value;
    }


    /**
     * Gets the value of the slotType property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getSlotType() {
        return slotType;
    }


    /**
     * Sets the value of the slotType property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setSlotType(CimString value) {
        this.slotType = value;
    }


    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Object } {@link Element }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }


    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }


    public CimString getFqdd() {
        return fqdd;
    }


    public void setFqdd(CimString fqdd) {
        this.fqdd = fqdd;
    }


    public CimString getPciDeviceID() {
        return pciDeviceID;
    }


    public void setPciDeviceID(CimString pciDeviceID) {
        this.pciDeviceID = pciDeviceID;
    }


    public CimString getPciSubDeviceID() {
        return pciSubDeviceID;
    }


    public void setPciSubDeviceID(CimString pciSubDeviceID) {
        this.pciSubDeviceID = pciSubDeviceID;
    }


    public CimString getPciSubVendorID() {
        return pciSubVendorID;
    }


    public void setPciSubVendorID(CimString pciSubVendorID) {
        this.pciSubVendorID = pciSubVendorID;
    }


    public CimString getPciVendorID() {
        return pciVendorID;
    }


    public void setPciVendorID(CimString pciVendorID) {
        this.pciVendorID = pciVendorID;
    }


    public CimString getAutoNegotiation() {
        return autoNegotiation;
    }


    public void setAutoNegotiation(CimString autoNegotiation) {
        this.autoNegotiation = autoNegotiation;
    }


    public CimString getControllerBIOSVersion() {
        return controllerBIOSVersion;
    }


    public void setControllerBIOSVersion(CimString controllerBIOSVersion) {
        this.controllerBIOSVersion = controllerBIOSVersion;
    }


    public CimString getFamilyVersion() {
        return familyVersion;
    }


    public void setFamilyVersion(CimString familyVersion) {
        this.familyVersion = familyVersion;
    }


    public CimString getLinkDuplex() {
        return linkDuplex;
    }


    public void setLinkDuplex(CimString linkDuplex) {
        this.linkDuplex = linkDuplex;
    }


    public CimString getLinkSpeed() {
        return linkSpeed;
    }


    public void setLinkSpeed(CimString linkSpeed) {
        this.linkSpeed = linkSpeed;
    }


    public CimString getMaxBandwidth() {
        return maxBandwidth;
    }


    public void setMaxBandwidth(CimString maxBandwidth) {
        this.maxBandwidth = maxBandwidth;
    }


    public CimString getNicMode() {
        return nicMode;
    }


    public void setNicMode(CimString nicMode) {
        this.nicMode = nicMode;
    }


    public CimString getTransmitFlowControl() {
        return transmitFlowControl;
    }


    public void setTransmitFlowControl(CimString transmitFlowControl) {
        this.transmitFlowControl = transmitFlowControl;
    }


    public CimString getVendorName() {
        return vendorName;
    }


    public void setVendorName(CimString vendorName) {
        this.vendorName = vendorName;
    }


    public CimString getVirtWwn() {
        return virtWwn;
    }


    public void setVirtWwn(CimString virtWwn) {
        this.virtWwn = virtWwn;
    }


    public CimString getVirtWwpn() {
        return virtWwpn;
    }


    public void setVirtWwpn(CimString virtWwpn) {
        this.virtWwpn = virtWwpn;
    }


    public CimString getfCoEOffloadMode() {
        return fCoEOffloadMode;
    }


    public void setfCoEOffloadMode(CimString fCoEOffloadMode) {
        this.fCoEOffloadMode = fCoEOffloadMode;
    }


    public CimString getfCoEWwnn() {
        return fCoEWwnn;
    }


    public void setfCoEWwnn(CimString fCoEWwnn) {
        this.fCoEWwnn = fCoEWwnn;
    }


    public CimString getiScsiOffloadMode() {
        return iScsiOffloadMode;
    }


    public void setiScsiOffloadMode(CimString iScsiOffloadMode) {
        this.iScsiOffloadMode = iScsiOffloadMode;
    }


    public CimString getMediaType() {
        return mediaType;
    }


    public void setMediaType(CimString mediaType) {
        this.mediaType = mediaType;
    }


    public CimString getMinBandwidth() {
        return minBandwidth;
    }


    public void setMinBandwidth(CimString minBandwidth) {
        this.minBandwidth = minBandwidth;
    }


    public CimString getReceiveFlowControl() {
        return receiveFlowControl;
    }


    public void setReceiveFlowControl(CimString receiveFlowControl) {
        this.receiveFlowControl = receiveFlowControl;
    }


    public CimString getWwn() {
        return wwn;
    }


    public void setWwn(CimString wwn) {
        this.wwn = wwn;
    }


    public CimString getWwpn() {
        return wwpn;
    }


    public void setWwpn(CimString wwpn) {
        this.wwpn = wwpn;
    }


    public String getLinkStatus() {
        return linkStatus;
    }


    public void setLinkStatus(String linkStatus) {
        this.linkStatus = linkStatus;
    }


    public String getOsDriverState() {
        return osDriverState;
    }


    public void setOsDriverState(String osDriverState) {
        this.osDriverState = osDriverState;
    }


    public String getMacAddress() {
        return macAddress;
    }


    public void setMacAddress(String macAddress) {
        this.macAddress = macAddress;
    }


    public String getIscsiMacAddress() {
        return iscsiMacAddress;
    }


    public void setIscsiMacAddress(String iscsiMacAddress) {
        this.iscsiMacAddress = iscsiMacAddress;
    }


    public String getVirtualMacAddress() {
        return virtualMacAddress;
    }


    public void setVirtualMacAddress(String virtualMacAddress) {
        this.virtualMacAddress = virtualMacAddress;
    }


    public String getVirtualIscsiMacAddress() {
        return virtualIscsiMacAddress;
    }


    public void setVirtualIscsiMacAddress(String virtualIscsiMacAddress) {
        this.virtualIscsiMacAddress = virtualIscsiMacAddress;
    }


    public String getTeaming() {
        return teaming;
    }


    public void setTeaming(String teaming) {
        this.teaming = teaming;
    }


    public String getIscsiOffloadSupport() {
        return iscsiOffloadSupport;
    }


    public void setIscsiOffloadSupport(String iscsiOffloadSupport) {
        this.iscsiOffloadSupport = iscsiOffloadSupport;
    }


    public String getToeSupport() {
        return toeSupport;
    }


    public void setToeSupport(String toeSupport) {
        this.toeSupport = toeSupport;
    }


    public String getLegacyBootProtocol() {
        return legacyBootProtocol;
    }


    public void setLegacyBootProtocol(String legacyBootProtocol) {
        this.legacyBootProtocol = legacyBootProtocol;
    }


    public String getIcsciBootMode() {
        return icsciBootMode;
    }


    public void setIcsciBootMode(String icsciBootMode) {
        this.icsciBootMode = icsciBootMode;
    }


    public String getIscsiInitiatorIpAddress() {
        return iscsiInitiatorIpAddress;
    }


    public void setIscsiInitiatorIpAddress(String iscsiInitiatorIpAddress) {
        this.iscsiInitiatorIpAddress = iscsiInitiatorIpAddress;
    }


    public String getIscsiInitiatorSubnet() {
        return iscsiInitiatorSubnet;
    }


    public void setIscsiInitiatorSubnet(String iscsiInitiatorSubnet) {
        this.iscsiInitiatorSubnet = iscsiInitiatorSubnet;
    }


    public String getIscsiInitiatorGateway() {
        return iscsiInitiatorGateway;
    }


    public void setIscsiInitiatorGateway(String iscsiInitiatorGateway) {
        this.iscsiInitiatorGateway = iscsiInitiatorGateway;
    }


    public String getIscsiInitiatorPrimaryDns() {
        return iscsiInitiatorPrimaryDns;
    }


    public void setIscsiInitiatorPrimaryDns(String iscsiInitiatorPrimaryDns) {
        this.iscsiInitiatorPrimaryDns = iscsiInitiatorPrimaryDns;
    }


    public String getIscsiInitiatorSecondryDns() {
        return iscsiInitiatorSecondryDns;
    }


    public void setIscsiInitiatorSecondryDns(String iscsiInitiatorSecondryDns) {
        this.iscsiInitiatorSecondryDns = iscsiInitiatorSecondryDns;
    }


    public String getIscsiInitiatorName() {
        return iscsiInitiatorName;
    }


    public void setIscsiInitiatorName(String iscsiInitiatorName) {
        this.iscsiInitiatorName = iscsiInitiatorName;
    }


    public void setOtherAttributes(Map<QName, String> otherAttributes) {
        this.otherAttributes = otherAttributes;
    }

}
