/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.23 at 08:16:53 PM CDT 
//

package com.dell.isg.smi.wsman.command.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for DCIM_DeviceView_Type complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DCIM_NICView_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}BusNumber" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}Caption" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}CurrentMACAddress" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}DataBusWidth" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}Description" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}DeviceNumber" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}ElementName" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}FQDD" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}FunctionNumber" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}Generation" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}InstanceID" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}LastSystemInventoryTime" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}LastUpdateTime" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}PCIDeviceID" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}PCISubDeviceID" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}PCISubVendorID" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}PCIVendorID" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}PermanentMACAddress" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}PermanentiSCSIMACAddress" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}ProductName" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}SlotLength" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_NICView}SlotType" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DCIM_PCIDeviceView_Type", namespace = "http://schemas.dell.com/wbem/wscim/1/cim-schema/2/DCIM_PCIDeviceView", propOrder = { "busNumber", "dataBusWidth", "description", "deviceNumber", "fqdd", "functionNumber", "instanceID", "lastSystemInventoryTime", "lastUpdateTime", "manufacturer", "pciDeviceID", "pciSubDeviceID", "pciSubVendorID", "pciVendorID", "slotLength", "slotType" })
public class DCIMPCIDeviceViewType {

    @XmlElement(name = "BusNumber", nillable = true)
    protected CimUnsignedByte busNumber;
    @XmlElement(name = "DataBusWidth", nillable = true)
    protected CimString dataBusWidth;
    @XmlElement(name = "Description", nillable = true)
    protected CimString description;
    @XmlElement(name = "DeviceNumber", nillable = true)
    protected CimUnsignedByte deviceNumber;
    @XmlElement(name = "FQDD", nillable = true)
    protected CimString fqdd;
    @XmlElement(name = "FunctionNumber", nillable = true)
    protected CimUnsignedByte functionNumber;
    @XmlElement(name = "InstanceID", nillable = true)
    protected CimString instanceID;
    @XmlElement(name = "LastSystemInventoryTime", nillable = true)
    protected CimString lastSystemInventoryTime;
    @XmlElement(name = "LastUpdateTime", nillable = true)
    protected CimString lastUpdateTime;
    @XmlElement(name = "Manufacturer", nillable = true)
    protected CimString manufacturer;
    @XmlElement(name = "PCIDeviceID", nillable = true)
    protected CimString pciDeviceID;
    @XmlElement(name = "PCISubDeviceID", nillable = true)
    protected CimString pciSubDeviceID;
    @XmlElement(name = "PCISubVendorID", nillable = true)
    protected CimString pciSubVendorID;
    @XmlElement(name = "PCIVendorID", nillable = true)
    protected CimString pciVendorID;
    @XmlElement(name = "SlotLength", nillable = true)
    protected CimString slotLength;
    @XmlElement(name = "SlotType", nillable = true)
    protected CimString slotType;


    // private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the busNumber property.
     * 
     * @return possible object is {@link CimUnsignedByte }
     * 
     */
    public CimUnsignedByte getBusNumber() {
        return busNumber;
    }


    /**
     * Sets the value of the busNumber property.
     * 
     * @param value allowed object is {@link CimUnsignedByte }
     * 
     */
    public void setBusNumber(CimUnsignedByte value) {
        this.busNumber = value;
    }


    /**
     * Gets the value of the dataBusWidth property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getDataBusWidth() {
        return dataBusWidth;
    }


    /**
     * Sets the value of the dataBusWidth property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setDataBusWidth(CimString value) {
        this.dataBusWidth = value;
    }


    /**
     * Gets the value of the description property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getDescription() {
        return description;
    }


    /**
     * Sets the value of the description property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setDescription(CimString value) {
        this.description = value;
    }


    /**
     * Gets the value of the deviceNumber property.
     * 
     * @return possible object is {@link CimUnsignedByte }
     * 
     */
    public CimUnsignedByte getDeviceNumber() {
        return deviceNumber;
    }


    /**
     * Sets the value of the deviceNumber property.
     * 
     * @param value allowed object is {@link CimUnsignedByte }
     * 
     */
    public void setDeviceNumber(CimUnsignedByte value) {
        this.deviceNumber = value;
    }


    /**
     * Gets the value of the fqdd property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getFQDD() {
        return fqdd;
    }


    /**
     * Sets the value of the fqdd property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setFQDD(CimString value) {
        this.fqdd = value;
    }


    /**
     * Gets the value of the functionNumber property.
     * 
     * @return possible object is {@link CimUnsignedByte }
     * 
     */
    public CimUnsignedByte getFunctionNumber() {
        return functionNumber;
    }


    /**
     * Sets the value of the functionNumber property.
     * 
     * @param value allowed object is {@link CimUnsignedByte }
     * 
     */
    public void setFunctionNumber(CimUnsignedByte value) {
        this.functionNumber = value;
    }


    /**
     * Gets the value of the instanceID property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getInstanceID() {
        return instanceID;
    }


    /**
     * Sets the value of the instanceID property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setInstanceID(CimString value) {
        this.instanceID = value;
    }


    /**
     * Gets the value of the lastSystemInventoryTime property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getLastSystemInventoryTime() {
        return lastSystemInventoryTime;
    }


    /**
     * Sets the value of the lastSystemInventoryTime property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setLastSystemInventoryTime(CimString value) {
        this.lastSystemInventoryTime = value;
    }


    /**
     * Gets the value of the lastUpdateTime property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getLastUpdateTime() {
        return lastUpdateTime;
    }


    /**
     * Sets the value of the lastUpdateTime property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setLastUpdateTime(CimString value) {
        this.lastUpdateTime = value;
    }


    public CimString getManufacturer() {
        return manufacturer;
    }


    public void setManufacturer(CimString value) {
        this.manufacturer = value;
    }


    /**
     * Gets the value of the pciDeviceID property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getPCIDeviceID() {
        return pciDeviceID;
    }


    /**
     * Sets the value of the pciDeviceID property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setPCIDeviceID(CimString value) {
        this.pciDeviceID = value;
    }


    /**
     * Gets the value of the pciSubDeviceID property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getPCISubDeviceID() {
        return pciSubDeviceID;
    }


    /**
     * Sets the value of the pciSubDeviceID property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setPCISubDeviceID(CimString value) {
        this.pciSubDeviceID = value;
    }


    /**
     * Gets the value of the pciSubVendorID property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getPCISubVendorID() {
        return pciSubVendorID;
    }


    /**
     * Sets the value of the pciSubVendorID property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setPCISubVendorID(CimString value) {
        this.pciSubVendorID = value;
    }


    /**
     * Gets the value of the pciVendorID property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getPCIVendorID() {
        return pciVendorID;
    }


    /**
     * Sets the value of the pciVendorID property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setPCIVendorID(CimString value) {
        this.pciVendorID = value;
    }


    /**
     * Gets the value of the slotLength property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getSlotLength() {
        return slotLength;
    }


    /**
     * Sets the value of the slotLength property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setSlotLength(CimString value) {
        this.slotLength = value;
    }


    /**
     * Gets the value of the slotType property.
     * 
     * @return possible object is {@link CimString }
     * 
     */
    public CimString getSlotType() {
        return slotType;
    }


    /**
     * Sets the value of the slotType property.
     * 
     * @param value allowed object is {@link CimString }
     * 
     */
    public void setSlotType(CimString value) {
        this.slotType = value;
    }

}
