/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.19 at 02:43:52 AM CDT 
//

package com.dell.isg.smi.wsman.command.entity;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the com.dell.pg.spectre.common.protocol.command.wsman.entity
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java representation of XML content can consist of schema
 * derived interfaces and classes representing the binding of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in this
 * class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OperatingStatus_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", "OperatingStatus");
    private final static QName _RequestedState_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", "RequestedState");
    private final static QName _Status_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", "Status");
    private final static QName _AvailableRequestedStates_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", "AvailableRequestedStates");
    private final static QName _InstallDate_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", "InstallDate");
    private final static QName _TimeOfLastStateChange_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", "TimeOfLastStateChange");
    private final static QName _EnabledState_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", "EnabledState");
    private final static QName _OtherEnabledState_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", "OtherEnabledState");
    private final static QName _Description_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", "Description");
    private final static QName _OperationalStatus_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", "OperationalStatus");
    private final static QName _InstanceID_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", "InstanceID");
    private final static QName _EnabledDefault_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", "EnabledDefault");
    private final static QName _PrimaryOwnerName_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", "PrimaryOwnerName");
    private final static QName _Generation_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", "Generation");
    private final static QName _PrimaryOwnerContact_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", "PrimaryOwnerContact");
    private final static QName _HealthState_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", "HealthState");
    private final static QName _TransitioningToState_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", "TransitioningToState");
    private final static QName _DetailedStatus_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", "DetailedStatus");
    private final static QName _PrimaryStatus_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", "PrimaryStatus");
    private final static QName _StatusDescriptions_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", "StatusDescriptions");
    private final static QName _DCIMBIOSService_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", "DCIM_BIOSService");
    private final static QName _Started_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", "Started");
    private final static QName _Caption_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", "Caption");
    private final static QName _StartMode_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", "StartMode");
    private final static QName _CommunicationStatus_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", "CommunicationStatus");
    private final static QName _ElementName_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", "ElementName");
    private final static QName _CimDateTimeCIMDateTime_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/common", "CIM_DateTime");


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dell.pg.spectre.common.protocol.command.wsman.entity
     * 
     */
    public ObjectFactory() {
    }


    /**
     * Create an instance of {@link RequestStateChangeINPUT.RequestedState }
     * 
     */
    public RequestStateChangeINPUT.RequestedState createRequestStateChangeINPUTRequestedState() {
        return new RequestStateChangeINPUT.RequestedState();
    }


    /**
     * Create an instance of {@link OperatingStatus }
     * 
     */
    public OperatingStatus createOperatingStatus() {
        return new OperatingStatus();
    }


    /**
     * Create an instance of {@link CimString }
     * 
     */
    public CimString createCimString() {
        return new CimString();
    }


    /**
     * Create an instance of {@link QualifierString }
     * 
     */
    public QualifierString createQualifierString() {
        return new QualifierString();
    }


    /**
     * Create an instance of {@link CimUnsignedByte }
     * 
     */
    public CimUnsignedByte createCimUnsignedByte() {
        return new CimUnsignedByte();
    }


    /**
     * Create an instance of {@link ChangeAffectedElementsAssignedSequenceINPUT }
     * 
     */
    public ChangeAffectedElementsAssignedSequenceINPUT createChangeAffectedElementsAssignedSequenceINPUT() {
        return new ChangeAffectedElementsAssignedSequenceINPUT();
    }


    /**
     * Create an instance of {@link StopServiceINPUT }
     * 
     */
    public StopServiceINPUT createStopServiceINPUT() {
        return new StopServiceINPUT();
    }


    /**
     * Create an instance of {@link CreateTargetedConfigJobOUTPUT.ReturnValue }
     * 
     */
    public CreateTargetedConfigJobOUTPUT.ReturnValue createCreateTargetedConfigJobOUTPUTReturnValue() {
        return new CreateTargetedConfigJobOUTPUT.ReturnValue();
    }


    /**
     * Create an instance of {@link PrimaryOwnerName }
     * 
     */
    public PrimaryOwnerName createPrimaryOwnerName() {
        return new PrimaryOwnerName();
    }


    /**
     * Create an instance of {@link SetBIOSAttributesINPUT.PasswordEncoding }
     * 
     */
    public SetBIOSAttributesINPUT.PasswordEncoding createSetBIOSAttributesINPUTPasswordEncoding() {
        return new SetBIOSAttributesINPUT.PasswordEncoding();
    }


    /**
     * Create an instance of {@link QualifierSArray }
     * 
     */
    public QualifierSArray createQualifierSArray() {
        return new QualifierSArray();
    }


    /**
     * Create an instance of {@link CimHexBinary }
     * 
     */
    public CimHexBinary createCimHexBinary() {
        return new CimHexBinary();
    }


    /**
     * Create an instance of {@link RestoreBIOSDefaultsINPUT.PasswordEncoding }
     * 
     */
    public RestoreBIOSDefaultsINPUT.PasswordEncoding createRestoreBIOSDefaultsINPUTPasswordEncoding() {
        return new RestoreBIOSDefaultsINPUT.PasswordEncoding();
    }


    /**
     * Create an instance of {@link CimChar16 }
     * 
     */
    public CimChar16 createCimChar16() {
        return new CimChar16();
    }


    /**
     * Create an instance of {@link CommunicationStatus }
     * 
     */
    public CommunicationStatus createCommunicationStatus() {
        return new CommunicationStatus();
    }


    /**
     * Create an instance of {@link CreateTargetedConfigJobINPUT }
     * 
     */
    public CreateTargetedConfigJobINPUT createCreateTargetedConfigJobINPUT() {
        return new CreateTargetedConfigJobINPUT();
    }


    /**
     * Create an instance of {@link QualifierUInt32 }
     * 
     */
    public QualifierUInt32 createQualifierUInt32() {
        return new QualifierUInt32();
    }


    /**
     * Create an instance of {@link CimDouble }
     * 
     */
    public CimDouble createCimDouble() {
        return new CimDouble();
    }


    /**
     * Create an instance of {@link ReadRawBIOSDataINPUT }
     * 
     */
    public ReadRawBIOSDataINPUT createReadRawBIOSDataINPUT() {
        return new ReadRawBIOSDataINPUT();
    }


    /**
     * Create an instance of {@link CimLong }
     * 
     */
    public CimLong createCimLong() {
        return new CimLong();
    }


    /**
     * Create an instance of {@link OperationalStatus }
     * 
     */
    public OperationalStatus createOperationalStatus() {
        return new OperationalStatus();
    }


    /**
     * Create an instance of {@link SetBIOSAttributeEmbeddedInstanceOUTPUT }
     * 
     */
    public SetBIOSAttributeEmbeddedInstanceOUTPUT createSetBIOSAttributeEmbeddedInstanceOUTPUT() {
        return new SetBIOSAttributeEmbeddedInstanceOUTPUT();
    }


    /**
     * Create an instance of {@link SetBIOSAttributeINPUT }
     * 
     */
    public SetBIOSAttributeINPUT createSetBIOSAttributeINPUT() {
        return new SetBIOSAttributeINPUT();
    }


    /**
     * Create an instance of {@link PrimaryOwnerContact }
     * 
     */
    public PrimaryOwnerContact createPrimaryOwnerContact() {
        return new PrimaryOwnerContact();
    }


    /**
     * Create an instance of {@link CimAnySimpleType }
     * 
     */
    public CimAnySimpleType createCimAnySimpleType() {
        return new CimAnySimpleType();
    }


    /**
     * Create an instance of {@link SetBIOSAttributeEmbeddedInstanceINPUT }
     * 
     */
    public SetBIOSAttributeEmbeddedInstanceINPUT createSetBIOSAttributeEmbeddedInstanceINPUT() {
        return new SetBIOSAttributeEmbeddedInstanceINPUT();
    }


    /**
     * Create an instance of {@link ReadRawBIOSDataOUTPUT.ReturnValue }
     * 
     */
    public ReadRawBIOSDataOUTPUT.ReturnValue createReadRawBIOSDataOUTPUTReturnValue() {
        return new ReadRawBIOSDataOUTPUT.ReturnValue();
    }


    /**
     * Create an instance of {@link DetailedStatus }
     * 
     */
    public DetailedStatus createDetailedStatus() {
        return new DetailedStatus();
    }


    /**
     * Create an instance of {@link SetAttributeOUTPUT }
     * 
     */
    public SetAttributeOUTPUT createSetAttributeOUTPUT() {
        return new SetAttributeOUTPUT();
    }


    /**
     * Create an instance of {@link CreationClassName }
     * 
     */
    public CreationClassName createCreationClassName() {
        return new CreationClassName();
    }


    /**
     * Create an instance of {@link WriteRawBIOSDataOUTPUT.ReturnValue }
     * 
     */
    public WriteRawBIOSDataOUTPUT.ReturnValue createWriteRawBIOSDataOUTPUTReturnValue() {
        return new WriteRawBIOSDataOUTPUT.ReturnValue();
    }


    /**
     * Create an instance of {@link DeletePendingConfigurationOUTPUT }
     * 
     */
    public DeletePendingConfigurationOUTPUT createDeletePendingConfigurationOUTPUT() {
        return new DeletePendingConfigurationOUTPUT();
    }


    /**
     * Create an instance of {@link SetBIOSAttributeOUTPUT }
     * 
     */
    public SetBIOSAttributeOUTPUT createSetBIOSAttributeOUTPUT() {
        return new SetBIOSAttributeOUTPUT();
    }


    /**
     * Create an instance of {@link Caption }
     * 
     */
    public Caption createCaption() {
        return new Caption();
    }


    /**
     * Create an instance of {@link CimFloat }
     * 
     */
    public CimFloat createCimFloat() {
        return new CimFloat();
    }


    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }


    /**
     * Create an instance of {@link SystemCreationClassName }
     * 
     */
    public SystemCreationClassName createSystemCreationClassName() {
        return new SystemCreationClassName();
    }


    /**
     * Create an instance of {@link CimInt }
     * 
     */
    public CimInt createCimInt() {
        return new CimInt();
    }


    /**
     * Create an instance of {@link CimBase64Binary }
     * 
     */
    public CimBase64Binary createCimBase64Binary() {
        return new CimBase64Binary();
    }


    /**
     * Create an instance of {@link RequestStateChangeOUTPUT }
     * 
     */
    public RequestStateChangeOUTPUT createRequestStateChangeOUTPUT() {
        return new RequestStateChangeOUTPUT();
    }


    /**
     * Create an instance of {@link TransitioningToState }
     * 
     */
    public TransitioningToState createTransitioningToState() {
        return new TransitioningToState();
    }


    /**
     * Create an instance of {@link com.dell.isg.smi.wsman.command.entity.RequestedState }
     * 
     */
    public com.dell.isg.smi.wsman.command.entity.RequestedState createRequestedState() {
        return new com.dell.isg.smi.wsman.command.entity.RequestedState();
    }


    /**
     * Create an instance of {@link ChangeAffectedElementsAssignedSequenceOUTPUT }
     * 
     */
    public ChangeAffectedElementsAssignedSequenceOUTPUT createChangeAffectedElementsAssignedSequenceOUTPUT() {
        return new ChangeAffectedElementsAssignedSequenceOUTPUT();
    }


    /**
     * Create an instance of {@link SetBIOSAttributeOUTPUT.SetResult }
     * 
     */
    public SetBIOSAttributeOUTPUT.SetResult createSetBIOSAttributeOUTPUTSetResult() {
        return new SetBIOSAttributeOUTPUT.SetResult();
    }


    /**
     * Create an instance of {@link DeletePendingConfigurationINPUT }
     * 
     */
    public DeletePendingConfigurationINPUT createDeletePendingConfigurationINPUT() {
        return new DeletePendingConfigurationINPUT();
    }


    /**
     * Create an instance of {@link CreateTargetedConfigJobOUTPUT }
     * 
     */
    public CreateTargetedConfigJobOUTPUT createCreateTargetedConfigJobOUTPUT() {
        return new CreateTargetedConfigJobOUTPUT();
    }


    /**
     * Create an instance of {@link StartServiceINPUT }
     * 
     */
    public StartServiceINPUT createStartServiceINPUT() {
        return new StartServiceINPUT();
    }


    /**
     * Create an instance of {@link SetBIOSAttributeEmbeddedInstanceINPUT.PasswordEncoding }
     * 
     */
    public SetBIOSAttributeEmbeddedInstanceINPUT.PasswordEncoding createSetBIOSAttributeEmbeddedInstanceINPUTPasswordEncoding() {
        return new SetBIOSAttributeEmbeddedInstanceINPUT.PasswordEncoding();
    }


    /**
     * Create an instance of {@link SetAttributeINPUT }
     * 
     */
    public SetAttributeINPUT createSetAttributeINPUT() {
        return new SetAttributeINPUT();
    }


    /**
     * Create an instance of {@link SetBIOSAttributesOUTPUT }
     * 
     */
    public SetBIOSAttributesOUTPUT createSetBIOSAttributesOUTPUT() {
        return new SetBIOSAttributesOUTPUT();
    }


    /**
     * Create an instance of {@link RestoreBIOSDefaultsINPUT }
     * 
     */
    public RestoreBIOSDefaultsINPUT createRestoreBIOSDefaultsINPUT() {
        return new RestoreBIOSDefaultsINPUT();
    }


    /**
     * Create an instance of {@link CimShort }
     * 
     */
    public CimShort createCimShort() {
        return new CimShort();
    }


    /**
     * Create an instance of {@link SystemName }
     * 
     */
    public SystemName createSystemName() {
        return new SystemName();
    }


    /**
     * Create an instance of {@link SetBIOSAttributeINPUT.PasswordEncoding }
     * 
     */
    public SetBIOSAttributeINPUT.PasswordEncoding createSetBIOSAttributeINPUTPasswordEncoding() {
        return new SetBIOSAttributeINPUT.PasswordEncoding();
    }


    /**
     * Create an instance of {@link EnabledState }
     * 
     */
    public EnabledState createEnabledState() {
        return new EnabledState();
    }


    /**
     * Create an instance of {@link RestoreBIOSDefaultsOUTPUT.ReturnValue }
     * 
     */
    public RestoreBIOSDefaultsOUTPUT.ReturnValue createRestoreBIOSDefaultsOUTPUTReturnValue() {
        return new RestoreBIOSDefaultsOUTPUT.ReturnValue();
    }


    /**
     * Create an instance of {@link StartMode }
     * 
     */
    public StartMode createStartMode() {
        return new StartMode();
    }


    /**
     * Create an instance of {@link RestoreBIOSDefaultsOUTPUT }
     * 
     */
    public RestoreBIOSDefaultsOUTPUT createRestoreBIOSDefaultsOUTPUT() {
        return new RestoreBIOSDefaultsOUTPUT();
    }


    /**
     * Create an instance of {@link WriteRawBIOSDataINPUT.PasswordEncoding }
     * 
     */
    public WriteRawBIOSDataINPUT.PasswordEncoding createWriteRawBIOSDataINPUTPasswordEncoding() {
        return new WriteRawBIOSDataINPUT.PasswordEncoding();
    }


    /**
     * Create an instance of {@link RequestStateChangeOUTPUT.ReturnValue }
     * 
     */
    public RequestStateChangeOUTPUT.ReturnValue createRequestStateChangeOUTPUTReturnValue() {
        return new RequestStateChangeOUTPUT.ReturnValue();
    }


    /**
     * Create an instance of {@link AvailableRequestedStates }
     * 
     */
    public AvailableRequestedStates createAvailableRequestedStates() {
        return new AvailableRequestedStates();
    }


    /**
     * Create an instance of {@link CimUnsignedInt }
     * 
     */
    public CimUnsignedInt createCimUnsignedInt() {
        return new CimUnsignedInt();
    }


    /**
     * Create an instance of {@link ReadRawBIOSDataOUTPUT }
     * 
     */
    public ReadRawBIOSDataOUTPUT createReadRawBIOSDataOUTPUT() {
        return new ReadRawBIOSDataOUTPUT();
    }


    /**
     * Create an instance of {@link SetBIOSAttributesOUTPUT.ReturnValue }
     * 
     */
    public SetBIOSAttributesOUTPUT.ReturnValue createSetBIOSAttributesOUTPUTReturnValue() {
        return new SetBIOSAttributesOUTPUT.ReturnValue();
    }


    /**
     * Create an instance of {@link QualifierBoolean }
     * 
     */
    public QualifierBoolean createQualifierBoolean() {
        return new QualifierBoolean();
    }


    /**
     * Create an instance of {@link SetAttributesOUTPUT }
     * 
     */
    public SetAttributesOUTPUT createSetAttributesOUTPUT() {
        return new SetAttributesOUTPUT();
    }


    /**
     * Create an instance of {@link DCIMBIOSServiceType }
     * 
     */
    public DCIMBIOSServiceType createDCIMBIOSServiceType() {
        return new DCIMBIOSServiceType();
    }


    /**
     * Create an instance of {@link CimReference }
     * 
     */
    public CimReference createCimReference() {
        return new CimReference();
    }


    /**
     * Create an instance of {@link CimUnsignedLong }
     * 
     */
    public CimUnsignedLong createCimUnsignedLong() {
        return new CimUnsignedLong();
    }


    /**
     * Create an instance of {@link SetBIOSAttributesINPUT }
     * 
     */
    public SetBIOSAttributesINPUT createSetBIOSAttributesINPUT() {
        return new SetBIOSAttributesINPUT();
    }


    /**
     * Create an instance of {@link WriteRawBIOSDataINPUT }
     * 
     */
    public WriteRawBIOSDataINPUT createWriteRawBIOSDataINPUT() {
        return new WriteRawBIOSDataINPUT();
    }


    /**
     * Create an instance of {@link CimByte }
     * 
     */
    public CimByte createCimByte() {
        return new CimByte();
    }


    /**
     * Create an instance of {@link RequestStateChangeINPUT }
     * 
     */
    public RequestStateChangeINPUT createRequestStateChangeINPUT() {
        return new RequestStateChangeINPUT();
    }


    /**
     * Create an instance of {@link SetBIOSAttributeEmbeddedInstanceOUTPUT.ReturnValue }
     * 
     */
    public SetBIOSAttributeEmbeddedInstanceOUTPUT.ReturnValue createSetBIOSAttributeEmbeddedInstanceOUTPUTReturnValue() {
        return new SetBIOSAttributeEmbeddedInstanceOUTPUT.ReturnValue();
    }


    /**
     * Create an instance of {@link SetBIOSAttributeOUTPUT.ReturnValue }
     * 
     */
    public SetBIOSAttributeOUTPUT.ReturnValue createSetBIOSAttributeOUTPUTReturnValue() {
        return new SetBIOSAttributeOUTPUT.ReturnValue();
    }


    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }


    /**
     * Create an instance of {@link PrimaryStatus }
     * 
     */
    public PrimaryStatus createPrimaryStatus() {
        return new PrimaryStatus();
    }


    /**
     * Create an instance of {@link QualifierSInt64 }
     * 
     */
    public QualifierSInt64 createQualifierSInt64() {
        return new QualifierSInt64();
    }


    /**
     * Create an instance of {@link CimDateTime }
     * 
     */
    public CimDateTime createCimDateTime() {
        return new CimDateTime();
    }


    /**
     * Create an instance of {@link HealthState }
     * 
     */
    public HealthState createHealthState() {
        return new HealthState();
    }


    /**
     * Create an instance of {@link SetAttributesINPUT }
     * 
     */
    public SetAttributesINPUT createSetAttributesINPUT() {
        return new SetAttributesINPUT();
    }


    /**
     * Create an instance of {@link CimUnsignedShort }
     * 
     */
    public CimUnsignedShort createCimUnsignedShort() {
        return new CimUnsignedShort();
    }


    /**
     * Create an instance of {@link CimBoolean }
     * 
     */
    public CimBoolean createCimBoolean() {
        return new CimBoolean();
    }


    /**
     * Create an instance of {@link SetBIOSAttributeEmbeddedInstanceOUTPUT.SetResult }
     * 
     */
    public SetBIOSAttributeEmbeddedInstanceOUTPUT.SetResult createSetBIOSAttributeEmbeddedInstanceOUTPUTSetResult() {
        return new SetBIOSAttributeEmbeddedInstanceOUTPUT.SetResult();
    }


    /**
     * Create an instance of {@link DeletePendingConfigurationOUTPUT.ReturnValue }
     * 
     */
    public DeletePendingConfigurationOUTPUT.ReturnValue createDeletePendingConfigurationOUTPUTReturnValue() {
        return new DeletePendingConfigurationOUTPUT.ReturnValue();
    }


    /**
     * Create an instance of {@link EnabledDefault }
     * 
     */
    public EnabledDefault createEnabledDefault() {
        return new EnabledDefault();
    }


    /**
     * Create an instance of {@link StopServiceOUTPUT }
     * 
     */
    public StopServiceOUTPUT createStopServiceOUTPUT() {
        return new StopServiceOUTPUT();
    }


    /**
     * Create an instance of {@link WriteRawBIOSDataOUTPUT }
     * 
     */
    public WriteRawBIOSDataOUTPUT createWriteRawBIOSDataOUTPUT() {
        return new WriteRawBIOSDataOUTPUT();
    }


    /**
     * Create an instance of {@link ChangeAffectedElementsAssignedSequenceOUTPUT.ReturnValue }
     * 
     */
    public ChangeAffectedElementsAssignedSequenceOUTPUT.ReturnValue createChangeAffectedElementsAssignedSequenceOUTPUTReturnValue() {
        return new ChangeAffectedElementsAssignedSequenceOUTPUT.ReturnValue();
    }


    /**
     * Create an instance of {@link StartServiceOUTPUT }
     * 
     */
    public StartServiceOUTPUT createStartServiceOUTPUT() {
        return new StartServiceOUTPUT();
    }


    /**
     * Create an instance of {@link SetAttributeOUTPUT.ReturnValue }
     * 
     */
    public SetAttributeOUTPUT.ReturnValue createSetAttributeOUTPUTReturnValue() {
        return new SetAttributeOUTPUT.ReturnValue();
    }


    /**
     * Create an instance of {@link SetBIOSAttributesOUTPUT.SetResult }
     * 
     */
    public SetBIOSAttributesOUTPUT.SetResult createSetBIOSAttributesOUTPUTSetResult() {
        return new SetBIOSAttributesOUTPUT.SetResult();
    }


    /**
     * Create an instance of {@link SetAttributesOUTPUT.ReturnValue }
     * 
     */
    public SetAttributesOUTPUT.ReturnValue createSetAttributesOUTPUTReturnValue() {
        return new SetAttributesOUTPUT.ReturnValue();
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OperatingStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", name = "OperatingStatus")
    public JAXBElement<OperatingStatus> createOperatingStatus(OperatingStatus value) {
        return new JAXBElement<OperatingStatus>(_OperatingStatus_QNAME, OperatingStatus.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link com.dell.isg.smi.wsman.command.entity.RequestedState }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", name = "RequestedState")
    public JAXBElement<com.dell.isg.smi.wsman.command.entity.RequestedState> createRequestedState(com.dell.isg.smi.wsman.command.entity.RequestedState value) {
        return new JAXBElement<com.dell.isg.smi.wsman.command.entity.RequestedState>(_RequestedState_QNAME, com.dell.isg.smi.wsman.command.entity.RequestedState.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Status }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", name = "Status")
    public JAXBElement<Status> createStatus(Status value) {
        return new JAXBElement<Status>(_Status_QNAME, Status.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AvailableRequestedStates }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", name = "AvailableRequestedStates")
    public JAXBElement<AvailableRequestedStates> createAvailableRequestedStates(AvailableRequestedStates value) {
        return new JAXBElement<AvailableRequestedStates>(_AvailableRequestedStates_QNAME, AvailableRequestedStates.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimDateTime }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", name = "InstallDate")
    public JAXBElement<CimDateTime> createInstallDate(CimDateTime value) {
        return new JAXBElement<CimDateTime>(_InstallDate_QNAME, CimDateTime.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimDateTime }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", name = "TimeOfLastStateChange")
    public JAXBElement<CimDateTime> createTimeOfLastStateChange(CimDateTime value) {
        return new JAXBElement<CimDateTime>(_TimeOfLastStateChange_QNAME, CimDateTime.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnabledState }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", name = "EnabledState")
    public JAXBElement<EnabledState> createEnabledState(EnabledState value) {
        return new JAXBElement<EnabledState>(_EnabledState_QNAME, EnabledState.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", name = "OtherEnabledState")
    public JAXBElement<CimString> createOtherEnabledState(CimString value) {
        return new JAXBElement<CimString>(_OtherEnabledState_QNAME, CimString.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", name = "Description")
    public JAXBElement<CimString> createDescription(CimString value) {
        return new JAXBElement<CimString>(_Description_QNAME, CimString.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OperationalStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", name = "OperationalStatus")
    public JAXBElement<OperationalStatus> createOperationalStatus(OperationalStatus value) {
        return new JAXBElement<OperationalStatus>(_OperationalStatus_QNAME, OperationalStatus.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", name = "InstanceID")
    public JAXBElement<CimString> createInstanceID(CimString value) {
        return new JAXBElement<CimString>(_InstanceID_QNAME, CimString.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnabledDefault }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", name = "EnabledDefault")
    public JAXBElement<EnabledDefault> createEnabledDefault(EnabledDefault value) {
        return new JAXBElement<EnabledDefault>(_EnabledDefault_QNAME, EnabledDefault.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrimaryOwnerName }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", name = "PrimaryOwnerName")
    public JAXBElement<PrimaryOwnerName> createPrimaryOwnerName(PrimaryOwnerName value) {
        return new JAXBElement<PrimaryOwnerName>(_PrimaryOwnerName_QNAME, PrimaryOwnerName.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimUnsignedLong }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", name = "Generation")
    public JAXBElement<CimUnsignedLong> createGeneration(CimUnsignedLong value) {
        return new JAXBElement<CimUnsignedLong>(_Generation_QNAME, CimUnsignedLong.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrimaryOwnerContact }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", name = "PrimaryOwnerContact")
    public JAXBElement<PrimaryOwnerContact> createPrimaryOwnerContact(PrimaryOwnerContact value) {
        return new JAXBElement<PrimaryOwnerContact>(_PrimaryOwnerContact_QNAME, PrimaryOwnerContact.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HealthState }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", name = "HealthState")
    public JAXBElement<HealthState> createHealthState(HealthState value) {
        return new JAXBElement<HealthState>(_HealthState_QNAME, HealthState.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransitioningToState }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", name = "TransitioningToState")
    public JAXBElement<TransitioningToState> createTransitioningToState(TransitioningToState value) {
        return new JAXBElement<TransitioningToState>(_TransitioningToState_QNAME, TransitioningToState.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DetailedStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", name = "DetailedStatus")
    public JAXBElement<DetailedStatus> createDetailedStatus(DetailedStatus value) {
        return new JAXBElement<DetailedStatus>(_DetailedStatus_QNAME, DetailedStatus.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrimaryStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", name = "PrimaryStatus")
    public JAXBElement<PrimaryStatus> createPrimaryStatus(PrimaryStatus value) {
        return new JAXBElement<PrimaryStatus>(_PrimaryStatus_QNAME, PrimaryStatus.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", name = "StatusDescriptions")
    public JAXBElement<CimString> createStatusDescriptions(CimString value) {
        return new JAXBElement<CimString>(_StatusDescriptions_QNAME, CimString.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DCIMBIOSServiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", name = "DCIM_BIOSService")
    public JAXBElement<DCIMBIOSServiceType> createDCIMBIOSService(DCIMBIOSServiceType value) {
        return new JAXBElement<DCIMBIOSServiceType>(_DCIMBIOSService_QNAME, DCIMBIOSServiceType.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimBoolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", name = "Started")
    public JAXBElement<CimBoolean> createStarted(CimBoolean value) {
        return new JAXBElement<CimBoolean>(_Started_QNAME, CimBoolean.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Caption }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", name = "Caption")
    public JAXBElement<Caption> createCaption(Caption value) {
        return new JAXBElement<Caption>(_Caption_QNAME, Caption.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StartMode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", name = "StartMode")
    public JAXBElement<StartMode> createStartMode(StartMode value) {
        return new JAXBElement<StartMode>(_StartMode_QNAME, StartMode.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommunicationStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", name = "CommunicationStatus")
    public JAXBElement<CommunicationStatus> createCommunicationStatus(CommunicationStatus value) {
        return new JAXBElement<CommunicationStatus>(_CommunicationStatus_QNAME, CommunicationStatus.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_BIOSService", name = "ElementName")
    public JAXBElement<CimString> createElementName(CimString value) {
        return new JAXBElement<CimString>(_ElementName_QNAME, CimString.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/common", name = "CIM_DateTime", scope = CimDateTime.class)
    public JAXBElement<String> createCimDateTimeCIMDateTime(String value) {
        return new JAXBElement<String>(_CimDateTimeCIMDateTime_QNAME, String.class, CimDateTime.class, value);
    }

}
