/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.23 at 10:40:01 AM CDT 
//

package com.dell.isg.smi.wsman.command.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for SetBIOSAttributes_OUTPUT_Type complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SetBIOSAttributes_OUTPUT_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SetResult">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;restriction base="&lt;http://schemas.dmtf.org/wbem/wscim/1/common>cimAnySimpleType">
 *                 &lt;anyAttribute processContents='lax'/>
 *               &lt;/restriction>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ReturnValue">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;restriction base="&lt;http://schemas.dmtf.org/wbem/wscim/1/common>cimAnySimpleType">
 *                 &lt;anyAttribute processContents='lax'/>
 *               &lt;/restriction>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SetBIOSAttributes_OUTPUT_Type", propOrder = { "setResult", "returnValue" })
public class SetBIOSAttributesOUTPUTType {

    @XmlElement(name = "SetResult", required = true, nillable = true)
    protected SetBIOSAttributesOUTPUTType.SetResult setResult;
    @XmlElement(name = "ReturnValue", required = true, nillable = true)
    protected SetBIOSAttributesOUTPUTType.ReturnValue returnValue;


    /**
     * Gets the value of the setResult property.
     * 
     * @return possible object is {@link SetBIOSAttributesOUTPUTType.SetResult }
     * 
     */
    public SetBIOSAttributesOUTPUTType.SetResult getSetResult() {
        return setResult;
    }


    /**
     * Sets the value of the setResult property.
     * 
     * @param value allowed object is {@link SetBIOSAttributesOUTPUTType.SetResult }
     * 
     */
    public void setSetResult(SetBIOSAttributesOUTPUTType.SetResult value) {
        this.setResult = value;
    }


    /**
     * Gets the value of the returnValue property.
     * 
     * @return possible object is {@link SetBIOSAttributesOUTPUTType.ReturnValue }
     * 
     */
    public SetBIOSAttributesOUTPUTType.ReturnValue getReturnValue() {
        return returnValue;
    }


    /**
     * Sets the value of the returnValue property.
     * 
     * @param value allowed object is {@link SetBIOSAttributesOUTPUTType.ReturnValue }
     * 
     */
    public void setReturnValue(SetBIOSAttributesOUTPUTType.ReturnValue value) {
        this.returnValue = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;restriction base="&lt;http://schemas.dmtf.org/wbem/wscim/1/common>cimAnySimpleType">
     *       &lt;anyAttribute processContents='lax'/>
     *     &lt;/restriction>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ReturnValue extends CimAnySimpleType {

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;restriction base="&lt;http://schemas.dmtf.org/wbem/wscim/1/common>cimAnySimpleType">
     *       &lt;anyAttribute processContents='lax'/>
     *     &lt;/restriction>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class SetResult extends CimAnySimpleType {

    }

}
