/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.27 at 11:23:03 AM IST 
//

package com.dell.isg.smi.wsman.command.entity.computersystem;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * com.dell.pg.spectre.common.protocol.command.wsman.entity.computersystem package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java representation of XML content can consist of schema
 * derived interfaces and classes representing the binding of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in this
 * class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CimDateTimeCIMDateTime_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/common", "CIM_DateTime");
    private final static QName _CommunicationStatus_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", "CommunicationStatus");
    private final static QName _ElementName_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", "ElementName");
    private final static QName _ResetCapability_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", "ResetCapability");
    private final static QName _Caption_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", "Caption");
    private final static QName _CIMComputerSystem_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", "CIM_ComputerSystem");
    private final static QName _OtherDedicatedDescriptions_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", "OtherDedicatedDescriptions");
    private final static QName _PowerManagementCapabilities_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", "PowerManagementCapabilities");
    private final static QName _PrimaryStatus_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", "PrimaryStatus");
    private final static QName _Roles_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", "Roles");
    private final static QName _StatusDescriptions_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", "StatusDescriptions");
    private final static QName _NameFormat_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", "NameFormat");
    private final static QName _TransitioningToState_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", "TransitioningToState");
    private final static QName _IdentifyingDescriptions_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", "IdentifyingDescriptions");
    private final static QName _OtherIdentifyingInfo_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", "OtherIdentifyingInfo");
    private final static QName _DetailedStatus_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", "DetailedStatus");
    private final static QName _PrimaryOwnerContact_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", "PrimaryOwnerContact");
    private final static QName _HealthState_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", "HealthState");
    private final static QName _OperationalStatus_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", "OperationalStatus");
    private final static QName _Description_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", "Description");
    private final static QName _OtherEnabledState_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", "OtherEnabledState");
    private final static QName _PrimaryOwnerName_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", "PrimaryOwnerName");
    private final static QName _InstanceID_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", "InstanceID");
    private final static QName _EnabledDefault_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", "EnabledDefault");
    private final static QName _TimeOfLastStateChange_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", "TimeOfLastStateChange");
    private final static QName _EnabledState_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", "EnabledState");
    private final static QName _InstallDate_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", "InstallDate");
    private final static QName _Status_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", "Status");
    private final static QName _AvailableRequestedStates_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", "AvailableRequestedStates");
    private final static QName _RequestedState_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", "RequestedState");
    private final static QName _OperatingStatus_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", "OperatingStatus");
    private final static QName _Dedicated_QNAME = new QName("http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", "Dedicated");


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
     * com.dell.pg.spectre.common.protocol.command.wsman.entity.computersystem
     * 
     */
    public ObjectFactory() {
    }


    /**
     * Create an instance of {@link CimFloat }
     * 
     */
    public CimFloat createCimFloat() {
        return new CimFloat();
    }


    /**
     * Create an instance of {@link CimUnsignedByte }
     * 
     */
    public CimUnsignedByte createCimUnsignedByte() {
        return new CimUnsignedByte();
    }


    /**
     * Create an instance of {@link com.dell.isg.smi.wsman.command.entity.computersystem.RequestedState }
     * 
     */
    public com.dell.isg.smi.wsman.command.entity.computersystem.RequestedState createRequestedState() {
        return new com.dell.isg.smi.wsman.command.entity.computersystem.RequestedState();
    }


    /**
     * Create an instance of {@link CimShort }
     * 
     */
    public CimShort createCimShort() {
        return new CimShort();
    }


    /**
     * Create an instance of {@link QualifierSArray }
     * 
     */
    public QualifierSArray createQualifierSArray() {
        return new QualifierSArray();
    }


    /**
     * Create an instance of {@link CimReference }
     * 
     */
    public CimReference createCimReference() {
        return new CimReference();
    }


    /**
     * Create an instance of {@link HealthState }
     * 
     */
    public HealthState createHealthState() {
        return new HealthState();
    }


    /**
     * Create an instance of {@link CIMComputerSystemType }
     * 
     */
    public CIMComputerSystemType createCIMComputerSystemType() {
        return new CIMComputerSystemType();
    }


    /**
     * Create an instance of {@link CimBase64Binary }
     * 
     */
    public CimBase64Binary createCimBase64Binary() {
        return new CimBase64Binary();
    }


    /**
     * Create an instance of {@link SetPowerStateINPUT.PowerState }
     * 
     */
    public SetPowerStateINPUT.PowerState createSetPowerStateINPUTPowerState() {
        return new SetPowerStateINPUT.PowerState();
    }


    /**
     * Create an instance of {@link CimByte }
     * 
     */
    public CimByte createCimByte() {
        return new CimByte();
    }


    /**
     * Create an instance of {@link PowerManagementCapabilities }
     * 
     */
    public PowerManagementCapabilities createPowerManagementCapabilities() {
        return new PowerManagementCapabilities();
    }


    /**
     * Create an instance of {@link CommunicationStatus }
     * 
     */
    public CommunicationStatus createCommunicationStatus() {
        return new CommunicationStatus();
    }


    /**
     * Create an instance of {@link CimUnsignedShort }
     * 
     */
    public CimUnsignedShort createCimUnsignedShort() {
        return new CimUnsignedShort();
    }


    /**
     * Create an instance of {@link CimLong }
     * 
     */
    public CimLong createCimLong() {
        return new CimLong();
    }


    /**
     * Create an instance of {@link CimChar16 }
     * 
     */
    public CimChar16 createCimChar16() {
        return new CimChar16();
    }


    /**
     * Create an instance of {@link TransitioningToState }
     * 
     */
    public TransitioningToState createTransitioningToState() {
        return new TransitioningToState();
    }


    /**
     * Create an instance of {@link OtherIdentifyingInfo }
     * 
     */
    public OtherIdentifyingInfo createOtherIdentifyingInfo() {
        return new OtherIdentifyingInfo();
    }


    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }


    /**
     * Create an instance of {@link CimUnsignedInt }
     * 
     */
    public CimUnsignedInt createCimUnsignedInt() {
        return new CimUnsignedInt();
    }


    /**
     * Create an instance of {@link RequestStateChangeOUTPUT.ReturnValue }
     * 
     */
    public RequestStateChangeOUTPUT.ReturnValue createRequestStateChangeOUTPUTReturnValue() {
        return new RequestStateChangeOUTPUT.ReturnValue();
    }


    /**
     * Create an instance of {@link CimHexBinary }
     * 
     */
    public CimHexBinary createCimHexBinary() {
        return new CimHexBinary();
    }


    /**
     * Create an instance of {@link QualifierBoolean }
     * 
     */
    public QualifierBoolean createQualifierBoolean() {
        return new QualifierBoolean();
    }


    /**
     * Create an instance of {@link CimString }
     * 
     */
    public CimString createCimString() {
        return new CimString();
    }


    /**
     * Create an instance of {@link Dedicated }
     * 
     */
    public Dedicated createDedicated() {
        return new Dedicated();
    }


    /**
     * Create an instance of {@link CimInt }
     * 
     */
    public CimInt createCimInt() {
        return new CimInt();
    }


    /**
     * Create an instance of {@link QualifierUInt32 }
     * 
     */
    public QualifierUInt32 createQualifierUInt32() {
        return new QualifierUInt32();
    }


    /**
     * Create an instance of {@link OperationalStatus }
     * 
     */
    public OperationalStatus createOperationalStatus() {
        return new OperationalStatus();
    }


    /**
     * Create an instance of {@link PrimaryOwnerName }
     * 
     */
    public PrimaryOwnerName createPrimaryOwnerName() {
        return new PrimaryOwnerName();
    }


    /**
     * Create an instance of {@link DetailedStatus }
     * 
     */
    public DetailedStatus createDetailedStatus() {
        return new DetailedStatus();
    }


    /**
     * Create an instance of {@link PrimaryOwnerContact }
     * 
     */
    public PrimaryOwnerContact createPrimaryOwnerContact() {
        return new PrimaryOwnerContact();
    }


    /**
     * Create an instance of {@link RequestStateChangeINPUT }
     * 
     */
    public RequestStateChangeINPUT createRequestStateChangeINPUT() {
        return new RequestStateChangeINPUT();
    }


    /**
     * Create an instance of {@link Caption }
     * 
     */
    public Caption createCaption() {
        return new Caption();
    }


    /**
     * Create an instance of {@link SetPowerStateINPUT }
     * 
     */
    public SetPowerStateINPUT createSetPowerStateINPUT() {
        return new SetPowerStateINPUT();
    }


    /**
     * Create an instance of {@link ResetCapability }
     * 
     */
    public ResetCapability createResetCapability() {
        return new ResetCapability();
    }


    /**
     * Create an instance of {@link OperatingStatus }
     * 
     */
    public OperatingStatus createOperatingStatus() {
        return new OperatingStatus();
    }


    /**
     * Create an instance of {@link CimAnySimpleType }
     * 
     */
    public CimAnySimpleType createCimAnySimpleType() {
        return new CimAnySimpleType();
    }


    /**
     * Create an instance of {@link NameFormat }
     * 
     */
    public NameFormat createNameFormat() {
        return new NameFormat();
    }


    /**
     * Create an instance of {@link RequestStateChangeINPUT.RequestedState }
     * 
     */
    public RequestStateChangeINPUT.RequestedState createRequestStateChangeINPUTRequestedState() {
        return new RequestStateChangeINPUT.RequestedState();
    }


    /**
     * Create an instance of {@link QualifierSInt64 }
     * 
     */
    public QualifierSInt64 createQualifierSInt64() {
        return new QualifierSInt64();
    }


    /**
     * Create an instance of {@link AvailableRequestedStates }
     * 
     */
    public AvailableRequestedStates createAvailableRequestedStates() {
        return new AvailableRequestedStates();
    }


    /**
     * Create an instance of {@link SetPowerStateOUTPUT }
     * 
     */
    public SetPowerStateOUTPUT createSetPowerStateOUTPUT() {
        return new SetPowerStateOUTPUT();
    }


    /**
     * Create an instance of {@link CimUnsignedLong }
     * 
     */
    public CimUnsignedLong createCimUnsignedLong() {
        return new CimUnsignedLong();
    }


    /**
     * Create an instance of {@link EnabledDefault }
     * 
     */
    public EnabledDefault createEnabledDefault() {
        return new EnabledDefault();
    }


    /**
     * Create an instance of {@link PrimaryStatus }
     * 
     */
    public PrimaryStatus createPrimaryStatus() {
        return new PrimaryStatus();
    }


    /**
     * Create an instance of {@link CimDateTime }
     * 
     */
    public CimDateTime createCimDateTime() {
        return new CimDateTime();
    }


    /**
     * Create an instance of {@link EnabledState }
     * 
     */
    public EnabledState createEnabledState() {
        return new EnabledState();
    }


    /**
     * Create an instance of {@link QualifierString }
     * 
     */
    public QualifierString createQualifierString() {
        return new QualifierString();
    }


    /**
     * Create an instance of {@link CimBoolean }
     * 
     */
    public CimBoolean createCimBoolean() {
        return new CimBoolean();
    }


    /**
     * Create an instance of {@link RequestStateChangeOUTPUT }
     * 
     */
    public RequestStateChangeOUTPUT createRequestStateChangeOUTPUT() {
        return new RequestStateChangeOUTPUT();
    }


    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }


    /**
     * Create an instance of {@link CreationClassName }
     * 
     */
    public CreationClassName createCreationClassName() {
        return new CreationClassName();
    }


    /**
     * Create an instance of {@link CimDouble }
     * 
     */
    public CimDouble createCimDouble() {
        return new CimDouble();
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/common", name = "CIM_DateTime", scope = CimDateTime.class)
    public JAXBElement<String> createCimDateTimeCIMDateTime(String value) {
        return new JAXBElement<String>(_CimDateTimeCIMDateTime_QNAME, String.class, CimDateTime.class, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommunicationStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", name = "CommunicationStatus")
    public JAXBElement<CommunicationStatus> createCommunicationStatus(CommunicationStatus value) {
        return new JAXBElement<CommunicationStatus>(_CommunicationStatus_QNAME, CommunicationStatus.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", name = "ElementName")
    public JAXBElement<CimString> createElementName(CimString value) {
        return new JAXBElement<CimString>(_ElementName_QNAME, CimString.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResetCapability }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", name = "ResetCapability")
    public JAXBElement<ResetCapability> createResetCapability(ResetCapability value) {
        return new JAXBElement<ResetCapability>(_ResetCapability_QNAME, ResetCapability.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Caption }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", name = "Caption")
    public JAXBElement<Caption> createCaption(Caption value) {
        return new JAXBElement<Caption>(_Caption_QNAME, Caption.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CIMComputerSystemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", name = "CIM_ComputerSystem")
    public JAXBElement<CIMComputerSystemType> createCIMComputerSystem(CIMComputerSystemType value) {
        return new JAXBElement<CIMComputerSystemType>(_CIMComputerSystem_QNAME, CIMComputerSystemType.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", name = "OtherDedicatedDescriptions")
    public JAXBElement<CimString> createOtherDedicatedDescriptions(CimString value) {
        return new JAXBElement<CimString>(_OtherDedicatedDescriptions_QNAME, CimString.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PowerManagementCapabilities }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", name = "PowerManagementCapabilities")
    public JAXBElement<PowerManagementCapabilities> createPowerManagementCapabilities(PowerManagementCapabilities value) {
        return new JAXBElement<PowerManagementCapabilities>(_PowerManagementCapabilities_QNAME, PowerManagementCapabilities.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrimaryStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", name = "PrimaryStatus")
    public JAXBElement<PrimaryStatus> createPrimaryStatus(PrimaryStatus value) {
        return new JAXBElement<PrimaryStatus>(_PrimaryStatus_QNAME, PrimaryStatus.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", name = "Roles")
    public JAXBElement<CimString> createRoles(CimString value) {
        return new JAXBElement<CimString>(_Roles_QNAME, CimString.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", name = "StatusDescriptions")
    public JAXBElement<CimString> createStatusDescriptions(CimString value) {
        return new JAXBElement<CimString>(_StatusDescriptions_QNAME, CimString.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameFormat }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", name = "NameFormat")
    public JAXBElement<NameFormat> createNameFormat(NameFormat value) {
        return new JAXBElement<NameFormat>(_NameFormat_QNAME, NameFormat.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransitioningToState }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", name = "TransitioningToState")
    public JAXBElement<TransitioningToState> createTransitioningToState(TransitioningToState value) {
        return new JAXBElement<TransitioningToState>(_TransitioningToState_QNAME, TransitioningToState.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", name = "IdentifyingDescriptions")
    public JAXBElement<CimString> createIdentifyingDescriptions(CimString value) {
        return new JAXBElement<CimString>(_IdentifyingDescriptions_QNAME, CimString.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OtherIdentifyingInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", name = "OtherIdentifyingInfo")
    public JAXBElement<OtherIdentifyingInfo> createOtherIdentifyingInfo(OtherIdentifyingInfo value) {
        return new JAXBElement<OtherIdentifyingInfo>(_OtherIdentifyingInfo_QNAME, OtherIdentifyingInfo.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DetailedStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", name = "DetailedStatus")
    public JAXBElement<DetailedStatus> createDetailedStatus(DetailedStatus value) {
        return new JAXBElement<DetailedStatus>(_DetailedStatus_QNAME, DetailedStatus.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrimaryOwnerContact }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", name = "PrimaryOwnerContact")
    public JAXBElement<PrimaryOwnerContact> createPrimaryOwnerContact(PrimaryOwnerContact value) {
        return new JAXBElement<PrimaryOwnerContact>(_PrimaryOwnerContact_QNAME, PrimaryOwnerContact.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HealthState }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", name = "HealthState")
    public JAXBElement<HealthState> createHealthState(HealthState value) {
        return new JAXBElement<HealthState>(_HealthState_QNAME, HealthState.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OperationalStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", name = "OperationalStatus")
    public JAXBElement<OperationalStatus> createOperationalStatus(OperationalStatus value) {
        return new JAXBElement<OperationalStatus>(_OperationalStatus_QNAME, OperationalStatus.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", name = "Description")
    public JAXBElement<CimString> createDescription(CimString value) {
        return new JAXBElement<CimString>(_Description_QNAME, CimString.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", name = "OtherEnabledState")
    public JAXBElement<CimString> createOtherEnabledState(CimString value) {
        return new JAXBElement<CimString>(_OtherEnabledState_QNAME, CimString.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrimaryOwnerName }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", name = "PrimaryOwnerName")
    public JAXBElement<PrimaryOwnerName> createPrimaryOwnerName(PrimaryOwnerName value) {
        return new JAXBElement<PrimaryOwnerName>(_PrimaryOwnerName_QNAME, PrimaryOwnerName.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", name = "InstanceID")
    public JAXBElement<CimString> createInstanceID(CimString value) {
        return new JAXBElement<CimString>(_InstanceID_QNAME, CimString.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnabledDefault }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", name = "EnabledDefault")
    public JAXBElement<EnabledDefault> createEnabledDefault(EnabledDefault value) {
        return new JAXBElement<EnabledDefault>(_EnabledDefault_QNAME, EnabledDefault.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimDateTime }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", name = "TimeOfLastStateChange")
    public JAXBElement<CimDateTime> createTimeOfLastStateChange(CimDateTime value) {
        return new JAXBElement<CimDateTime>(_TimeOfLastStateChange_QNAME, CimDateTime.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnabledState }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", name = "EnabledState")
    public JAXBElement<EnabledState> createEnabledState(EnabledState value) {
        return new JAXBElement<EnabledState>(_EnabledState_QNAME, EnabledState.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CimDateTime }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", name = "InstallDate")
    public JAXBElement<CimDateTime> createInstallDate(CimDateTime value) {
        return new JAXBElement<CimDateTime>(_InstallDate_QNAME, CimDateTime.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Status }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", name = "Status")
    public JAXBElement<Status> createStatus(Status value) {
        return new JAXBElement<Status>(_Status_QNAME, Status.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AvailableRequestedStates }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", name = "AvailableRequestedStates")
    public JAXBElement<AvailableRequestedStates> createAvailableRequestedStates(AvailableRequestedStates value) {
        return new JAXBElement<AvailableRequestedStates>(_AvailableRequestedStates_QNAME, AvailableRequestedStates.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link com.dell.isg.smi.wsman.command.entity.computersystem.RequestedState }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", name = "RequestedState")
    public JAXBElement<com.dell.isg.smi.wsman.command.entity.computersystem.RequestedState> createRequestedState(com.dell.isg.smi.wsman.command.entity.computersystem.RequestedState value) {
        return new JAXBElement<com.dell.isg.smi.wsman.command.entity.computersystem.RequestedState>(_RequestedState_QNAME, com.dell.isg.smi.wsman.command.entity.computersystem.RequestedState.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OperatingStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", name = "OperatingStatus")
    public JAXBElement<OperatingStatus> createOperatingStatus(OperatingStatus value) {
        return new JAXBElement<OperatingStatus>(_OperatingStatus_QNAME, OperatingStatus.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Dedicated }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem", name = "Dedicated")
    public JAXBElement<Dedicated> createDedicated(Dedicated value) {
        return new JAXBElement<Dedicated>(_Dedicated_QNAME, Dedicated.class, null, value);
    }

}
