/**
 * Copyright © 2017 DELL Inc. or its subsidiaries. All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.12.27 at 11:23:03 AM IST
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.dmtf.org/wbem/wscim/1/common", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.dell.isg.smi.wsman.command.entity.computersystem;
