/**
 * Copyright © 2017 DELL Inc. or its subsidiaries.  All Rights Reserved.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.24 at 03:10:03 PM CST 
//

package com.dell.isg.smi.wsman.command.entity.idracwsman;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Attribute complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Attribute">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InstanceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GroupID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GroupDisplayName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FQDD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DisplayOrder" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Dependency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DefaultValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CurrentValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AttributeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AttributeDisplayName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MaxLength" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MinLength" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LowerBound" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UpperBound" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PossibleValues" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="IsReadOnly" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Caption" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ElementName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IsOrderedList" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Attribute", propOrder = { "instanceID", "groupID", "groupDisplayName", "fqdd", "displayOrder", "dependency", "defaultValue", "currentValue", "attributeName", "attributeDisplayName", "maxLength", "minLength", "lowerBound", "upperBound", "possibleValues", "isReadOnly", "caption", "description", "elementName", "isOrderedList" })
public class Attribute {

    @XmlElement(name = "InstanceID", required = true)
    protected String instanceID;
    @XmlElement(name = "GroupID", required = true)
    protected String groupID;
    @XmlElement(name = "GroupDisplayName", required = true)
    protected String groupDisplayName;
    @XmlElement(name = "FQDD", required = true)
    protected String fqdd;
    @XmlElement(name = "DisplayOrder", required = true)
    protected String displayOrder;
    @XmlElement(name = "Dependency", required = true)
    protected String dependency;
    @XmlElement(name = "DefaultValue", required = true)
    protected String defaultValue;
    @XmlElement(name = "CurrentValue", required = true)
    protected String currentValue;
    @XmlElement(name = "AttributeName", required = true)
    protected String attributeName;
    @XmlElement(name = "AttributeDisplayName", required = true)
    protected String attributeDisplayName;
    @XmlElement(name = "MaxLength")
    protected String maxLength;
    @XmlElement(name = "MinLength")
    protected String minLength;
    @XmlElement(name = "LowerBound")
    protected String lowerBound;
    @XmlElement(name = "UpperBound")
    protected String upperBound;
    @XmlElement(name = "PossibleValues")
    protected List<String> possibleValues;
    @XmlElement(name = "IsReadOnly")
    protected String isReadOnly;
    @XmlElement(name = "Caption")
    protected String caption;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "ElementName")
    protected String elementName;
    @XmlElement(name = "IsOrderedList")
    protected String isOrderedList;


    /**
     * Gets the value of the instanceID property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getInstanceID() {
        return instanceID;
    }


    /**
     * Sets the value of the instanceID property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setInstanceID(String value) {
        this.instanceID = value;
    }


    /**
     * Gets the value of the groupID property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getGroupID() {
        return groupID;
    }


    /**
     * Sets the value of the groupID property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setGroupID(String value) {
        this.groupID = value;
    }


    /**
     * Gets the value of the groupDisplayName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getGroupDisplayName() {
        return groupDisplayName;
    }


    /**
     * Sets the value of the groupDisplayName property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setGroupDisplayName(String value) {
        this.groupDisplayName = value;
    }


    /**
     * Gets the value of the fqdd property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFQDD() {
        return fqdd;
    }


    /**
     * Sets the value of the fqdd property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setFQDD(String value) {
        this.fqdd = value;
    }


    /**
     * Gets the value of the displayOrder property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDisplayOrder() {
        return displayOrder;
    }


    /**
     * Sets the value of the displayOrder property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDisplayOrder(String value) {
        this.displayOrder = value;
    }


    /**
     * Gets the value of the dependency property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDependency() {
        return dependency;
    }


    /**
     * Sets the value of the dependency property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDependency(String value) {
        this.dependency = value;
    }


    /**
     * Gets the value of the defaultValue property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDefaultValue() {
        return defaultValue;
    }


    /**
     * Sets the value of the defaultValue property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDefaultValue(String value) {
        this.defaultValue = value;
    }


    /**
     * Gets the value of the currentValue property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCurrentValue() {
        return currentValue;
    }


    /**
     * Sets the value of the currentValue property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCurrentValue(String value) {
        this.currentValue = value;
    }


    /**
     * Gets the value of the attributeName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAttributeName() {
        return attributeName;
    }


    /**
     * Sets the value of the attributeName property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setAttributeName(String value) {
        this.attributeName = value;
    }


    /**
     * Gets the value of the attributeDisplayName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAttributeDisplayName() {
        return attributeDisplayName;
    }


    /**
     * Sets the value of the attributeDisplayName property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setAttributeDisplayName(String value) {
        this.attributeDisplayName = value;
    }


    /**
     * Gets the value of the maxLength property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMaxLength() {
        return maxLength;
    }


    /**
     * Sets the value of the maxLength property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setMaxLength(String value) {
        this.maxLength = value;
    }


    /**
     * Gets the value of the minLength property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMinLength() {
        return minLength;
    }


    /**
     * Sets the value of the minLength property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setMinLength(String value) {
        this.minLength = value;
    }


    /**
     * Gets the value of the lowerBound property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLowerBound() {
        return lowerBound;
    }


    /**
     * Sets the value of the lowerBound property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setLowerBound(String value) {
        this.lowerBound = value;
    }


    /**
     * Gets the value of the upperBound property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUpperBound() {
        return upperBound;
    }


    /**
     * Sets the value of the upperBound property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setUpperBound(String value) {
        this.upperBound = value;
    }


    /**
     * Gets the value of the possibleValues property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the possibleValues property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getPossibleValues().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     * 
     * 
     */
    public List<String> getPossibleValues() {
        if (possibleValues == null) {
            possibleValues = new ArrayList<String>();
        }
        return this.possibleValues;
    }


    /**
     * Gets the value of the isReadOnly property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIsReadOnly() {
        return isReadOnly;
    }


    /**
     * Sets the value of the isReadOnly property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setIsReadOnly(String value) {
        this.isReadOnly = value;
    }


    /**
     * Gets the value of the caption property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCaption() {
        return caption;
    }


    /**
     * Sets the value of the caption property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCaption(String value) {
        this.caption = value;
    }


    /**
     * Gets the value of the description property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDescription() {
        return description;
    }


    /**
     * Sets the value of the description property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDescription(String value) {
        this.description = value;
    }


    /**
     * Gets the value of the elementName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getElementName() {
        return elementName;
    }


    /**
     * Sets the value of the elementName property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setElementName(String value) {
        this.elementName = value;
    }


    /**
     * Gets the value of the isOrderedList property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIsOrderedList() {
        return isOrderedList;
    }


    /**
     * Sets the value of the isOrderedList property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setIsOrderedList(String value) {
        this.isOrderedList = value;
    }

}
